In [1]:
import numpy as np
import pandas as pd

from sklearn import datasets, tree

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

## 지역, 상품, 아이템별 14별 146개 아이템 추출

In [3]:
selloutData = pd.read_csv("../dataset2/kopo_decision_tree_all_new.csv")

In [2]:
groupKey = ["REGIONID","PRODUCTGROUP","PRODUCT","ITEM"]

In [8]:
groupData = selloutData.groupby(groupKey)["YEARWEEK"].agg(["size"]).reset_index()

In [9]:
groupData.rename(columns={"size":"KNOB"}, inplace=True)

In [13]:
groupData.head()

  REGIONID PRODUCTGROUP PRODUCT     ITEM  KNOB
0      A01         PG01     P01  ITEM001     3
1      A01         PG01     P01  ITEM002     2
2      A01         PG01     P01  ITEM003     1
3      A01         PG01     P01  ITEM004     7
4      A01         PG01     P01  ITEM005     8

In [12]:
mergedData = pd.merge(left=selloutData,
                        right=groupData,
                        on=groupKey,
                        how="left")

mergedData.head()

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,KNOB
0,A01,PG01,P01,ITEM001,201538,2015,38,1,N,4,N,0.0,3
1,A01,PG01,P01,ITEM001,201548,2015,48,1,Y,0,N,0.0,3
2,A01,PG01,P01,ITEM001,201549,2015,49,2,Y,0,N,0.0,3
3,A01,PG01,P01,ITEM002,201526,2015,26,1,Y,1,N,0.0,2
4,A01,PG01,P01,ITEM002,201532,2015,32,1,N,4,N,0.0,2

In [16]:
maxKnob = mergedData.KNOB.max()
maxKnob

146

In [19]:
refinedData = mergedData[mergedData.KNOB >= maxKnob]
len(refinedData)

7592

In [24]:
sortKey = ["REGIONID","PRODUCTGROUP","PRODUCT","ITEM","YEARWEEK"]

In [26]:
sortedData = refinedData.sort_values(sortKey).reset_index(drop=True)
sortedData.head()

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,KNOB
0,A01,PG02,P03,ITEM043,201501,2015,1,87,Y,1,Y,0.197590,146
1,A01,PG02,P03,ITEM043,201502,2015,2,60,N,4,Y,0.197590,146
2,A01,PG02,P03,ITEM043,201503,2015,3,51,N,4,N,0.000000,146
3,A01,PG02,P03,ITEM043,201504,2015,4,37,Y,2,N,0.000000,146
4,A01,PG02,P03,ITEM043,201505,2015,5,136,N,4,Y,0.201205,146

In [27]:
sortedData.YEARWEEK.min()

201501

In [29]:
sortedData.describe()

,YEARWEEK,YEAR,WEEK,QTY,HCLUS,PRO_PERCENT,KNOB
count,7592.000000,7592.000000,7592.000000,7592.000000,7592.000000,7592.000000,7592.0
mean,201616.917808,2015.917808,25.136986,173.690595,2.801370,0.242486,146.0
std,78.836685,0.798226,14.534164,338.459991,1.533384,0.116065,0.0
min,201501.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,146.0
25%,201537.000000,2015.000000,13.000000,18.000000,1.000000,0.180645,146.0
50%,201620.500000,2016.000000,25.000000,49.000000,4.000000,0.249953,146.0
75%,201705.000000,2017.000000,37.000000,175.000000,4.000000,0.318242,146.0
max,201741.000000,2017.000000,53.000000,5798.000000,4.000000,0.550644,146.0

In [46]:
stdYearweek = 201701

In [30]:
groupKey

['REGIONID', 'PRODUCTGROUP', 'PRODUCT', 'ITEM']

In [32]:
groupData2 = sortedData.groupby(groupKey)

In [33]:
groupData2.get_group(list(groupData2.groups)[0])

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,KNOB
0,A01,PG02,P03,ITEM043,201501,2015,1,87,Y,1,Y,0.197590,146
1,A01,PG02,P03,ITEM043,201502,2015,2,60,N,4,Y,0.197590,146
2,A01,PG02,P03,ITEM043,201503,2015,3,51,N,4,N,0.000000,146
3,A01,PG02,P03,ITEM043,201504,2015,4,37,Y,2,N,0.000000,146
4,A01,PG02,P03,ITEM043,201505,2015,5,136,N,4,Y,0.201205,146
5,A01,PG02,P03,ITEM043,201506,2015,6,117,N,4,Y,0.201205,146
6,A01,PG02,P03,ITEM043,201507,2015,7,106,N,4,Y,0.201205,146
7,A01,PG02,P03,ITEM043,201508,2015,8,56,Y,1,N,0.000000,146
8,A01,PG02,P03,ITEM043,201509,2015,9,70,N,4,N,0.000000,146
9,A01,PG02,P03,ITEM043,201510,2015,10,167,N,4,Y,0.201205,146
10,A01,PG02,P03,ITEM043,201511,2015,11,191,N,4,Y,0.201205,146
11,A01,PG02,P03,ITEM043,201512,2015,12,158,N,4,Y,0.201205,146
12,A01,PG02,P03,ITEM043,201513,2015,13,63,N,4,N,0.000000,146
13,A01,PG02,P03,ITEM043,201514,2015,14,55,N,4,N,0.000000,146
14,A01,PG02,P03,ITEM043,201515,2015,15,98,N,4,Y,0.201205,146
15,A01,PG02,P03,ITEM043,201516,2015,16,123,N,4,Y,0.201205,146
16,A01,PG02,P03,ITEM043,201517,2015,17,136,N,4,Y,0.201205,146
17,A01,PG02,P03,ITEM043,201518,2015,18,75,N,4,Y,0.201205,146
18,A01,PG02,P03,ITEM043,201519,2015,19,46,N,4,N,0.000000,146
19,A01,PG02,P03,ITEM043,201520,2015,20,32,Y,1,N,0.000000,146
20,A01,PG02,P03,ITEM043,201521,2015,21,50,Y,1,N,0.000000,146
21,A01,PG02,P03,ITEM043,201522,2015,22,57,Y,1,N,0.000000,146
22,A01,PG02,P03,ITEM043,201523,2015,23,187,N,4,Y,0.201205,146
23,A01,PG02,P03,ITEM043,201524,2015,24,168,N,4,Y,0.201205,146
24,A01,PG02,P03,ITEM043,201525,2015,25,235,Y,1,Y,0.201205,146
25,A01,PG02,P03,ITEM043,201526,2015,26,2216,Y,1,Y,0.403614,146
26,A01,PG02,P03,ITEM043,201527,2015,27,3691,Y,1,Y,0.403614,146
27,A01,PG02,P03,ITEM043,201528,2015,28,2034,Y,1,Y,0.403614,146
28,A01,PG02,P03,ITEM043,201529,2015,29,1705,Y,1,Y,0.403614,146
29,A01,PG02,P03,ITEM043,201530,2015,30,110,N,4,N,0.000000,146
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,A01,PG02,P03,ITEM043,201712,2017,12,322,N,4,Y,0.201205,146
117,A01,PG02,P03,ITEM043,201713,2017,13,366,N,4,Y,0.201205,146
118,A01,PG02,P03,ITEM043,201714,2017,14,500,N,4,Y,0.201205,146
119,A01,PG02,P03,ITEM043,201715,2017,15,323,N,4,Y,0.201205,146
120,A01,PG02,P03,ITEM043,201716,2017,16,170,N,4,Y,0.121687,146
121,A01,PG02,P03,ITEM043,201717,2017,17,203,N,4,Y,0.121687,146
122,A01,PG02,P03,ITEM043,201718,2017,18,201,N,4,Y,0.121687,146
123,A01,PG02,P03,ITEM043,201719,2017,19,151,N,4,N,0.000000,146
124,A01,PG02,P03,ITEM043,201720,2017,20,273,Y,1,Y,0.201205,146
125,A01,PG02,P03,ITEM043,201721,2017,21,590,Y,1,Y,0.201205,146
126,A01,PG02,P03,ITEM043,201722,2017,22,595,Y,1,Y,0.201205,146
127,A01,PG02,P03,ITEM043,201723,2017,23,399,N,4,Y,0.201205,146
128,A01,PG02,P03,ITEM043,201724,2017,24,241,N,4,Y,0.280723,146
129,A01,PG02,P03,ITEM043,201725,2017,25,447,Y,1,Y,0.280723,146
130,A01,PG02,P03,ITEM043,201726,2017,26,447,Y,1,Y,0.280723,146
131,A01,PG02,P03,ITEM043,201727,2017,27,548,Y,1,Y,0.280723,146
132,A01,PG02,P03,ITEM043,201728,2017,28,457,Y,1,Y,0.280723,146
133,A01,PG02,P03,ITEM043,201729,2017,29,423,Y,1,Y,0.280723,146
134,A01,PG02,P03,ITEM043,201730,2017,30,408,N,4,Y,0.201205,146
135,A01,PG02,P03,ITEM043,201731,2017,31,304,N,4,Y,0.201205,146
136,A01,PG02,P03,ITEM043,201732,2017,32,250,N,4,Y,0.201205,146
137,A01,PG02,P03,ITEM043,201733,2017,33,431,N,4,Y,0.280723,146
138,A01,PG02,P03,ITEM043,201734,2017,34,657,Y,1,Y,0.280723,146
139,A01,PG02,P03,ITEM043,201735,2017,35,658,Y,1,Y,0.280723,146
140,A01,PG02,P03,ITEM043,201736,2017,36,600,Y,1,Y,0.280723,146
141,A01,PG02,P03,ITEM043,201737,2017,37,396,N,4,Y,0.280723,146
142,A01,PG02,P03,ITEM043,201738,2017,38,116,N,4,N,0.000000,146
143,A01,PG02,P03,ITEM043,201739,2017,39,238,N,4,Y,0.280723,146
144,A01,PG02,P03,ITEM043,201740,2017,40,336,N,4,Y,0.280723,146
145,A01,PG02,P03,ITEM043,201741,2017,41,432,Y,2,Y,0.280723,146

In [55]:
def dtPredict(onegroup):
    onegroup = groupData2.get_group(list(groupData2.groups)[2])
    eachgroup = onegroup.reset_index(drop=True)
    
    corrdf = eachgroup.corr()
    corrStd = 0.5
    features = list(corrdf[ (abs(corrdf["QTY"] ) >= corrStd) & (corrdf["QTY"] != 1) ].index)
    label = ["QTY"]
    
    testData_all = eachgroup[ eachgroup.YEARWEEK >= stdYearweek ]
    testDataSize = len(testData_all)
    
    if testDataSize != 0:

        trainingData_features = eachgroup[ eachgroup.YEARWEEK < stdYearweek ][features]
        trainingData_label = eachgroup[ eachgroup.YEARWEEK < stdYearweek ][label]
        testData_features = eachgroup[ eachgroup.YEARWEEK >= stdYearweek ][features]
        testData_label = eachgroup[ eachgroup.YEARWEEK >= stdYearweek ][label]


        from sklearn import tree
        model_method = tree.DecisionTreeRegressor(random_state=32)
        model = model_method.fit(trainingData_features, trainingData_label)

        testData_all["PREDICT"] = model.predict(testData_features)

        return testData_all

In [ ]:
predictDF = sortedData.groupby(groupKey).apply(dtPredict)

In [34]:
onegroup = groupData2.get_group(list(groupData2.groups)[2])
eachgroup = onegroup.reset_index(drop=True)

##### 1. 특성 선별

In [44]:
corrdf = eachgroup.corr()
corrStd = 0.5
features = list(corrdf[ (abs(corrdf["QTY"] ) >= corrStd) & (corrdf["QTY"] != 1) ].index)
label = ["QTY"]

In [45]:
print(features)
print(label)

['HCLUS']
['QTY']

##### 2. 데이터 분리(훈련/테스트)

In [48]:
trainingData_features = eachgroup[ eachgroup.YEARWEEK < stdYearweek ][features]
trainingData_label = eachgroup[ eachgroup.YEARWEEK < stdYearweek ][label]
testData_features = eachgroup[ eachgroup.YEARWEEK >= stdYearweek ][features]
testData_label = eachgroup[ eachgroup.YEARWEEK >= stdYearweek ][label]
testData_all = eachgroup[ eachgroup.YEARWEEK >= stdYearweek ]

##### 3. 모델 선언

In [49]:
from sklearn import tree

In [50]:
model_method = tree.DecisionTreeRegressor(random_state=32)

##### 4. 훈련 (훈련데이터 특성/답지 활용)

In [51]:
model = model_method.fit(trainingData_features, trainingData_label)

##### 5. 예측 (테스트 데이터의 feature)

In [52]:
model.predict(testData_features)

array([29.        , 19.88888889, 23.75      , 19.88888889, 19.88888889,
       19.88888889, 19.88888889, 29.        , 19.88888889, 19.88888889,
       19.88888889, 19.88888889, 19.88888889, 19.88888889, 19.88888889,
       19.88888889, 19.88888889, 19.88888889, 19.88888889, 29.        ,
       29.        , 29.        , 19.88888889, 19.88888889, 29.        ,
       29.        , 29.        , 29.        , 29.        , 19.88888889,
       19.88888889, 19.88888889, 19.88888889, 29.        , 29.        ,
       29.        , 19.88888889, 19.88888889, 19.88888889, 19.88888889,
       23.75      ])

In [53]:
testData_all["PREDICT"] = model.predict(testData_features)

C:\Users\SMART-15\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [54]:
testData_all

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,KNOB,PREDICT
105,A01,PG02,P03,ITEM051,201701,2017,1,17,Y,1,Y,0.180645,146,29.000000
106,A01,PG02,P03,ITEM051,201702,2017,2,21,N,4,Y,0.180645,146,19.888889
107,A01,PG02,P03,ITEM051,201703,2017,3,18,Y,2,Y,0.180645,146,23.750000
108,A01,PG02,P03,ITEM051,201704,2017,4,32,N,4,Y,0.180645,146,19.888889
109,A01,PG02,P03,ITEM051,201705,2017,5,23,N,4,Y,0.145161,146,19.888889
110,A01,PG02,P03,ITEM051,201706,2017,6,25,N,4,Y,0.180645,146,19.888889
111,A01,PG02,P03,ITEM051,201707,2017,7,25,N,4,Y,0.180645,146,19.888889
112,A01,PG02,P03,ITEM051,201708,2017,8,39,Y,1,Y,0.180645,146,29.000000
113,A01,PG02,P03,ITEM051,201709,2017,9,22,N,4,Y,0.180645,146,19.888889
114,A01,PG02,P03,ITEM051,201710,2017,10,15,N,4,N,0.000000,146,19.888889
115,A01,PG02,P03,ITEM051,201711,2017,11,17,N,4,N,0.000000,146,19.888889
116,A01,PG02,P03,ITEM051,201712,2017,12,31,N,4,Y,0.180645,146,19.888889
117,A01,PG02,P03,ITEM051,201713,2017,13,24,N,4,Y,0.180645,146,19.888889
118,A01,PG02,P03,ITEM051,201714,2017,14,36,N,4,Y,0.180645,146,19.888889
119,A01,PG02,P03,ITEM051,201715,2017,15,24,N,4,Y,0.180645,146,19.888889
120,A01,PG02,P03,ITEM051,201716,2017,16,9,N,4,N,0.000000,146,19.888889
121,A01,PG02,P03,ITEM051,201717,2017,17,17,N,4,N,0.000000,146,19.888889
122,A01,PG02,P03,ITEM051,201718,2017,18,9,N,4,N,0.000000,146,19.888889
123,A01,PG02,P03,ITEM051,201719,2017,19,16,N,4,N,0.000000,146,19.888889
124,A01,PG02,P03,ITEM051,201720,2017,20,16,Y,1,Y,0.106452,146,29.000000
125,A01,PG02,P03,ITEM051,201721,2017,21,33,Y,1,Y,0.106452,146,29.000000
126,A01,PG02,P03,ITEM051,201722,2017,22,20,Y,1,Y,0.106452,146,29.000000
127,A01,PG02,P03,ITEM051,201723,2017,23,29,N,4,Y,0.106452,146,19.888889
128,A01,PG02,P03,ITEM051,201724,2017,24,18,N,4,N,0.000000,146,19.888889
129,A01,PG02,P03,ITEM051,201725,2017,25,38,Y,1,Y,0.287097,146,29.000000
130,A01,PG02,P03,ITEM051,201726,2017,26,36,Y,1,Y,0.287097,146,29.000000
131,A01,PG02,P03,ITEM051,201727,2017,27,58,Y,1,Y,0.287097,146,29.000000
132,A01,PG02,P03,ITEM051,201728,2017,28,47,Y,1,Y,0.287097,146,29.000000
133,A01,PG02,P03,ITEM051,201729,2017,29,16,Y,1,Y,0.287097,146,29.000000
134,A01,PG02,P03,ITEM051,201730,2017,30,25,N,4,Y,0.180645,146,19.888889
135,A01,PG02,P03,ITEM051,201731,2017,31,18,N,4,Y,0.180645,146,19.888889
136,A01,PG02,P03,ITEM051,201732,2017,32,20,N,4,Y,0.180645,146,19.888889
137,A01,PG02,P03,ITEM051,201733,2017,33,17,N,4,Y,0.216129,146,19.888889
138,A01,PG02,P03,ITEM051,201734,2017,34,20,Y,1,Y,0.216129,146,29.000000
139,A01,PG02,P03,ITEM051,201735,2017,35,28,Y,1,Y,0.216129,146,29.000000
140,A01,PG02,P03,ITEM051,201736,2017,36,35,Y,1,Y,0.216129,146,29.000000
141,A01,PG02,P03,ITEM051,201737,2017,37,21,N,4,Y,0.216129,146,19.888889
142,A01,PG02,P03,ITEM051,201738,2017,38,9,N,4,N,0.000000,146,19.888889
143,A01,PG02,P03,ITEM051,201739,2017,39,16,N,4,Y,0.216129,146,19.888889
144,A01,PG02,P03,ITEM051,201740,2017,40,23,N,4,Y,0.216129,146,19.888889
145,A01,PG02,P03,ITEM051,201741,2017,41,25,Y,2,Y,0.216129,146,23.750000