In [66]:
import pandas as pd
import numpy as np
import math

In [67]:
rawdata1 = pd.read_excel("../dataset/tourdata2017_1.xlsx")
rawdata2 = pd.read_excel("../dataset/tourdata2017_2.xlsx")
rawdata3 = pd.read_excel("../dataset/tourdata2017_3.xlsx")

## 1. 분석 데이터 생성

### 1-1. 데이터 정제

In [68]:
# 컬럼명 통일 (공백제거, 소문자 맞춤)

rawdata1.rename(columns=lambda x: x.strip().lower(), inplace=True)
rawdata2.rename(columns=lambda x: x.strip().lower(), inplace=True)
rawdata3.rename(columns=lambda x: x.strip().lower(), inplace=True)

In [69]:
# m_id 빈 값 지우기
# m_id 값이 null이면 다른 컬럼의 value도 null이기 때문에 해당 열을 삭제

rawdata2 = rawdata2.dropna(subset=["m_id"])
rawdata3 = rawdata3.dropna(subset=["m_id"])

In [70]:
#국내여행자만 선택해서 보기

rawdata2 = rawdata2[rawdata2["type1"] == 1]
rawdata3 = rawdata3[rawdata3["type1"] == 1]

In [71]:
# 필요한 컬럼만 선택해서 보기
# 분석에 불필요한 컬럼을 제거

rawdata1 = rawdata1.drop(['sr_type','ara_size', 'school1','school2','occ0','occ2','marry','fac','inc1_1','inc2_1','wt'], axis = 1)

In [72]:
# 필요한 컬럼만 선택해서 보기
# 분석에 불필요한 컬럼을 제거

rawdata2 = rawdata2.drop(['m_id','type2','q2_a','q2_a_1','q2_a_2','q2_b','q2_b_1','q2_b_1','q2_b_2','q2_c_1','q2_c_2','q2_1_1',
                          'q5_2_1','q5_2_2','q5_2_3','q5_2_4','q5_2_5','q5_2_6',
                          'q7_1','q7_3_1','q7_3_2','q7_3_3','q7_3_4','q7_3_5','q7_3_6','q7_3_7','q7_3_8','q7_3_9','q7_3_10',
                          'q2_1_2','q2_1_3','q2_1_4','q2_1_5','q4_1_a','q4_1_b','q9_2','wt'], axis = 1)

In [73]:
# 필요한 컬럼만 선택해서 보기
# 분석에 불필요한 컬럼을 제거

rawdata3 = rawdata3.drop(['m_id','type2','q6_1_1','q6_1_2','q6_1_3','q6_1_4','q6_1_5','q6_1_6','q6_1_7','q6_1_8',
                          'q6_5_1a','q6_5_2a','q6_5_3a','q6_5_4a','q6_5_5a','q6_5_6a','q6_5_7a','q6_5_8a','q6_5_9a','q6_5_10a',
                          'q6_5_11a','q6_5_12a','q6_5_13a','q7_2','wt'], axis = 1)

### 1-2. 1차 join = 단위여행 + 방문지

In [74]:
# 1차 join = 같은 응답자의 단위여행 데이터와, 방문지 데이터를 합친다.
# hid,pid,month가 같으면 해당데이터는 동일인물임

joinKey = ["hid","pid","month"]

In [75]:
firstmerge = pd.merge(rawdata2, rawdata3, left_on=joinKey, right_on=joinKey, how="left")

In [76]:
# 나이를 세대별로 구분하기 위해 새로운 컬럼 생성

rawdata1["age_group"] = np.where(rawdata1["age"]>0, (((rawdata1["age"]/10).astype(int))*10) , 0)

In [77]:
# 응답자 20대 추출

rawdata1 = rawdata1[rawdata1.age_group==20]

### 1-3. 2차 join = 응답자 + 1차 join

In [78]:
# 2차 join 데이터 = 같은 응답자의 응답자 정보와 1차 join 데이터를 합친다.
# hid,pid가 같으면 해당데이터는 동일인물임

joinKey2 = ["hid","pid"]

In [79]:
secondmerge = pd.merge(rawdata1, firstmerge, left_on=joinKey2, right_on=joinKey2, how="left")

In [80]:
# 총지출비용 컬럼이 null값인 데이터를 삭제

secondmerge = secondmerge.dropna(subset=["q7"])

In [81]:
secondmerge = secondmerge.reset_index(drop = True)

### 2-1. 직업 기준 생성

In [82]:
# 직업을 분류를 명확히하기 위해 대학생,직장인,무직,군인,무응답으로 재설정

jobCodeList = []

for i in range(0,len(secondmerge)):
    jobCode = 123
    job = secondmerge["occ1"][i]
    
    if ((job == 14) | (job == 15)):
        #대학생
        jobCode = 1
    elif job < 10:
        #직장인
        jobCode = 2
    elif job == 16:
        #무직
        jobCode = 3
    elif job == 10:
        #군인
        jobCode = 4
    else:
        jobCode = 999
    jobCodeList.append(jobCode)

In [83]:
columnName = "job_group"
tempDF = pd.DataFrame(jobCodeList, columns=[columnName])
secondmerge = pd.concat([secondmerge, tempDF], axis=1)

### 3-1. 만족도 기준 생성

In [84]:
# 항목별 만족도 컬럼이 null값인 데이터를 삭제
# 기존 만족도 데이터는 단편적이며 데이터를 분류하는데 어려움이 있기 때문에 새로운 만족도 기준을 생성

satisfaction = secondmerge.dropna(subset=["q10_1"]).reset_index(drop = True)

In [85]:
# 항목별 만족도에서 9.경험해보지 못함 -> 0으로 바꿈

satisfaction.loc[:,"q10_1":"q10_12"] = np.where(satisfaction.loc[:,"q10_1":"q10_12"] == 9,0,satisfaction.loc[:,"q10_1":"q10_12"])

In [86]:
# 항복별 만족도의 평균을 구한후 소수점 반올림후 2배하여 새로운 기준을 생성

tempList = []

for i in range(0,len(satisfaction)):
    zeroCount = 0
    for j in satisfaction.loc[i,"q10_1":"q10_12"]:
        if j==0:
            zeroCount += 1
    
    # 항목별 만족도, 전반적 만족도, 재방문의향, 추천의향에 가중치를 설정
    tempList.append(
     (round((math.pow((sum(satisfaction.loc[i,"q10_1":"q10_12"]) / (12-zeroCount)), 2)) * 10) / 10) * 1.2
     + (math.pow((satisfaction.loc[i,"q6_7"]), 2) * 1.6)
     + (math.pow((satisfaction.loc[i,"q6_8"]), 2) * 0.8)
     + (math.pow((satisfaction.loc[i,"q6_9"]), 2) * 0.4))

In [87]:
colName = "q10_grade"
tempDF = pd.DataFrame(tempList, columns=[colName])
result01 = pd.concat([satisfaction, tempDF], axis=1)

### 3-2. 숙박시설 컬럼 (망함 ㅠㅠ)

In [88]:
# result01["q6_5_1"] = result01["q6_5_1"].fillna(0)
# result01["q6_5_2"] =result01["q6_5_2"].fillna(0)
# result01["q6_5_3"] =result01["q6_5_3"].fillna(0)
# result01["q6_5_4"] =result01["q6_5_4"].fillna(0)
# result01["q6_5_5"] =result01["q6_5_5"].fillna(0)
# result01["q6_5_6"] =result01["q6_5_6"].fillna(0)
# result01["q6_5_7"] =result01["q6_5_7"].fillna(0)
# result01["q6_5_8"] =result01["q6_5_8"].fillna(0)
# result01["q6_5_9"] =result01["q6_5_9"].fillna(0)
# result01["q6_5_10"] =result01["q6_5_10"].fillna(0)
# result01["q6_5_11"] =result01["q6_5_11"].fillna(0)
# result01["q6_5_12"] =result01["q6_5_12"].fillna(0)
# result01["q6_5_13"] =result01["q6_5_13"].fillna(0)

In [89]:
# q6_List = []
# for i in range(0,len(result01)):
#     q6_List.append(sum(result01.loc[i,"q6_5_1":"q6_5_13"]))

In [90]:
# colName = "숙박시설"
# tempDF = pd.DataFrame(q6_List, columns=[colName])
# tempDF["숙박시설"] = tempDF["숙박시설"].astype(int)
# result01 = pd.concat([result01, tempDF], axis=1)

### 3-3. 일별 지출비용 등급

In [91]:
# 지출비용을 이용한 분류를 명확히 하기 위해 지출비용을 5단계로 설정
# 1 : 3만원 이하 
# 2 : 6만원 이하
# 3 : 10만원 이하
# 4 : 20만원 이하
# 5 : 이외 전부

tempList = []

for i in range(0,len(satisfaction)):
    q7 = result01.loc[i,"q7"]
    day = result01.loc[i,"q6_2"]
    temp = q7 / day
    
    if (temp <= 30000):
        grade = 1
    elif (temp <= 60000):
        grade = 2
    elif (temp <= 100000):
        grade = 3
    elif (temp <= 200000):
        grade = 4
    elif (temp > 200000):
        grade = 5
    
    tempList.append(grade)

In [92]:
colName = "q7_grade"
tempDF = pd.DataFrame(tempList, columns=[colName])
result01 = pd.concat([result01, tempDF], axis=1)

In [93]:
result01

,hid,pid,sex,age,sido,occ1,age_group,type1_x,month,q1,...,q6_6_18,q6_6_19,q6_6_20,q6_6_21,q6_7,q6_8,q6_9,job_group,q10_grade,q7_grade
0,10003,1000303,2,28,1,16,20,1.0,4.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,3.0,3,61.20,4
1,10019,1001904,2,23,1,14,20,1.0,4.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,3
2,10019,1001904,2,23,1,14,20,1.0,8.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,3
3,10031,1003105,1,21,1,14,20,1.0,3.0,2.0,...,NaN,NaN,NaN,NaN,5.0,5.0,5.0,1,89.20,2
4,10031,1003105,1,21,1,14,20,1.0,10.0,2.0,...,NaN,NaN,NaN,NaN,5.0,4.0,5.0,1,86.08,2
5,10031,1003105,1,21,1,14,20,1.0,10.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,68.08,2
6,10031,1003105,1,21,1,14,20,1.0,10.0,2.0,...,NaN,NaN,NaN,NaN,5.0,4.0,5.0,1,84.52,2
7,10031,1003105,1,21,1,14,20,1.0,10.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,66.52,2
8,10045,1004503,2,22,1,14,20,1.0,4.0,2.0,...,NaN,NaN,NaN,NaN,4.0,5.0,4.0,1,68.08,3
9,10045,1004503,2,22,1,14,20,1.0,6.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,62.44,3
10,10045,1004503,2,22,1,14,20,1.0,8.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,60.64,1
11,10056,1005604,2,23,1,14,20,1.0,5.0,2.0,...,NaN,NaN,NaN,NaN,5.0,5.0,5.0,1,89.20,2
12,10062,1006204,2,24,1,14,20,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,5
13,10062,1006204,2,24,1,14,20,1.0,8.0,1.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,2
14,10062,1006204,2,24,1,14,20,1.0,8.0,1.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,3
15,10062,1006204,2,24,1,14,20,1.0,8.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,2
16,10062,1006204,2,24,1,14,20,1.0,8.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,3
17,10062,1006204,2,24,1,14,20,1.0,9.0,1.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,2
18,10062,1006205,1,23,1,15,20,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,3.0,4.0,3.0,1,47.48,3
19,10062,1006205,1,23,1,15,20,1.0,5.0,1.0,...,NaN,NaN,NaN,NaN,3.0,3.0,3.0,1,37.44,4
20,10062,1006205,1,23,1,15,20,1.0,9.0,2.0,...,NaN,NaN,NaN,NaN,4.0,3.0,3.0,1,55.60,5
21,10062,1006205,1,23,1,15,20,1.0,9.0,2.0,...,NaN,NaN,NaN,NaN,3.0,3.0,3.0,1,44.40,5
22,10062,1006205,1,23,1,15,20,1.0,9.0,2.0,...,NaN,NaN,NaN,NaN,5.0,5.0,4.0,1,85.60,4
23,10086,1008604,1,29,1,5,20,1.0,8.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,2,64.00,4
24,10113,1011304,2,25,1,14,20,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,61.48,2
25,10113,1011304,2,25,1,14,20,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,60.64,3
26,10139,1013903,1,20,8,14,20,1.0,7.0,2.0,...,NaN,NaN,NaN,NaN,5.0,4.0,4.0,1,77.56,3
27,10139,1013903,1,20,8,14,20,1.0,7.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,63.16,3
28,10142,1014204,2,26,1,14,20,1.0,10.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,5.0,1,69.40,2
29,10146,1014603,2,29,1,3,20,1.0,5.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,2,64.00,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290,15257,1525704,1,29,8,14,20,1.0,8.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,61.48,1
1291,15259,1525903,2,22,8,14,20,1.0,3.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,59.44,2
1292,15259,1525903,2,22,8,14,20,1.0,6.0,2.0,...,NaN,NaN,NaN,NaN,4.0,5.0,5.0,1,72.52,2
1293,15259,1525903,2,22,8,14,20,1.0,12.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,65.68,3
1294,15259,1525904,1,20,8,14,20,1.0,6.0,1.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,59.92,3
1295,15265,1526503,1,20,8,14,20,1.0,12.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,65.68,3
1296,15283,1528303,2,21,8,14,20,1.0,2.0,1.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,64.00,1
1297,15294,1529403,1,25,8,14,20,1.0,8.0,1.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,3
1298,15296,1529603,2,26,8,3,20,1.0,5.0,1.0,...,NaN,NaN,NaN,NaN,4.0,3.0,4.0,2,52.76,4
1299,15296,1529603,2,26,8,3,20,1.0,8.0,2.0,...,NaN,NaN,NaN,NaN,5.0,5.0,5.0,2,91.72,2
1300,15296,1529603,2,26,8,3,20,1.0,10.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,2,70.00,3
1301,15324,1532404,2,20,8,14,20,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,61.48,2
1302,15324,1532404,2,20,8,14,20,1.0,4.0,2.0,...,NaN,NaN,20.0,NaN,3.0,3.0,3.0,1,36.00,1
1303,15327,1532703,2,25,8,14,20,1.0,5.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,60.88,4
1304,15331,1533103,1,25,10,10,20,1.0,11.0,1.0,...,NaN,NaN,NaN,NaN,3.0,3.0,3.0,4,37.08,3
1305,15331,1533103,1,25,10,10,20,1.0,12.0,2.0,...,NaN,NaN,NaN,NaN,3.0,3.0,3.0,4,44.40,3
1306,15331,1533104,1,22,10,8,20,1.0,12.0,1.0,...,NaN,NaN,NaN,NaN,4.0,4.0,3.0,2,55.32,2
1307,15348,1534803,2,21,11,14,20,1.0,10.0,1.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,59.08,4
1308,15348,1534803,2,21,11,14,20,1.0,12.0,2.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,63.16,3
1309,15370,1537003,2,21,12,14,20,1.0,5.0,2.0,...,NaN,NaN,NaN,NaN,5.0,4.0,4.0,1,76.84,3
1310,15380,1538003,1,26,15,14,20,1.0,2.0,2.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,59.92,4
1311,15380,1538003,1,26,15,14,20,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,59.92,5
1312,15380,1538003,1,26,15,14,20,1.0,2.0,1.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,62.92,2
1313,15380,1538003,1,26,15,14,20,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,62.92,3
1314,15380,1538003,1,26,15,14,20,1.0,4.0,2.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,57.88,4
1315,15380,1538003,1,26,15,14,20,1.0,6.0,2.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,58.36,4
1316,15380,1538003,1,26,15,14,20,1.0,10.0,2.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,56.32,3
1317,15380,1538004,1,23,15,14,20,1.0,8.0,1.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,60.40,3
1318,15380,1538004,1,23,15,14,20,1.0,10.0,1.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,61.24,3
1319,15380,1538004,1,23,15,14,20,1.0,12.0,1.0,...,NaN,NaN,20.0,NaN,4.0,4.0,4.0,1,56.32,4

In [94]:
result01.to_csv("../dataset/result_join.csv", index=False)

## 2. 데이터 모델링

### 2-1. 상관관계 분석

In [95]:
corrGroupKey = ["hid","pid",'month','age',"job_group" ]

In [96]:
tmp = result01.groupby(corrGroupKey).sum().reset_index(drop=False)

In [97]:
columnList = ['q10_grade','hid', 'pid', 'month', 'age', 'sex', 'sido', 'occ1',  
              'age_group', 'type1_x','type1_y', 'q1', 'q3', 'q4_a', 'q5_1', 'q7', 'q8', 'q8_1', 'q8_2', 'q8_3', 'q8_4', 
              'q8_5', 'q8_6', 'q8_7', 'q10_1', 'q10_2', 'q10_3', 'q10_4', 'q10_5', 'q10_6', 'q10_7', 'q10_8', 
              'q10_9', 'q10_10', 'q10_11', 'q10_12', 'q6_1', 'q6_2', 'q6_3_a', 'q6_3_b', 'q6_3_c', 'q6_4', 'q6_5_1', 'q6_5_2', 
              'q6_5_3', 'q6_5_4', 'q6_5_5', 'q6_5_6', 'q6_5_7', 'q6_5_8', 'q6_5_9', 'q6_5_10', 'q6_5_11', 'q6_5_12', 'q6_5_13', 
              'q6_6_1', 'q6_6_2', 'q6_6_3', 'q6_6_4', 'q6_6_5', 'q6_6_6', 'q6_6_7', 'q6_6_8', 'q6_6_9', 'q6_6_10', 
              'q6_6_11', 'q6_6_12', 'q6_6_13', 'q6_6_14', 'q6_6_15', 'q6_6_16', 'q6_6_17', 'q6_6_18', 'q6_6_19', 
              'q6_6_20', 'q6_6_21', 'q6_7', 'q6_8', 'q6_9']

In [98]:
tmp = tmp[columnList]

In [99]:
corrDF999 = tmp.corr()

In [100]:
corrDF999

,q10_grade,hid,pid,month,age,sex,sido,occ1,age_group,type1_x,...,q6_6_15,q6_6_16,q6_6_17,q6_6_18,q6_6_19,q6_6_20,q6_6_21,q6_7,q6_8,q6_9
q10_grade,1.000000,0.029657,0.028846,0.015492,0.092151,0.908744,0.899973,0.803357,0.983236,0.983236,...,-0.013952,0.015025,0.156450,0.113497,0.079809,0.045742,0.101527,0.995513,0.993762,0.994018
hid,0.029657,1.000000,0.978469,0.049624,-0.034502,0.037439,0.093005,0.072488,0.023511,0.023511,...,-0.010009,-0.018878,-0.002471,-0.014017,0.072504,0.105764,0.098794,0.024999,0.024070,0.024020
pid,0.028846,0.978469,1.000000,0.045290,-0.055726,0.030525,0.099414,0.080296,0.023440,0.023440,...,-0.011934,-0.015746,0.003014,-0.012733,0.076710,0.104775,0.103793,0.024951,0.023783,0.023438
month,0.015492,0.049624,0.045290,1.000000,-0.021127,0.016418,0.012802,0.004324,0.013563,0.013563,...,0.018693,-0.017495,-0.118221,0.001015,-0.036219,-0.085987,-0.063707,0.011181,0.011640,0.012231
age,0.092151,-0.034502,-0.055726,-0.021127,1.000000,0.044735,0.064695,-0.076685,0.076608,0.076608,...,-0.065653,-0.011086,0.086420,0.032479,-0.034368,-0.022936,-0.001968,0.086076,0.083145,0.086233
sex,0.908744,0.037439,0.030525,0.016418,0.044735,1.000000,0.799290,0.813947,0.912952,0.912952,...,-0.030875,-0.002528,0.150777,0.075783,0.037891,0.086612,0.131207,0.908396,0.915041,0.912728
sido,0.899973,0.093005,0.099414,0.012802,0.064695,0.799290,1.000000,0.714402,0.930371,0.930371,...,-0.021570,-0.016672,0.095528,0.084455,0.115472,0.045520,0.078295,0.919270,0.919591,0.919351
occ1,0.803357,0.072488,0.080296,0.004324,-0.076685,0.813947,0.714402,1.000000,0.799922,0.799922,...,0.019461,0.037225,0.183303,0.017153,0.123206,0.102503,0.179054,0.799020,0.804382,0.802323
age_group,0.983236,0.023511,0.023440,0.013563,0.076608,0.912952,0.930371,0.799922,1.000000,1.000000,...,-0.008563,0.011512,0.122023,0.117113,0.073111,0.056670,0.102740,0.994263,0.994196,0.993582
type1_x,0.983236,0.023511,0.023440,0.013563,0.076608,0.912952,0.930371,0.799922,1.000000,1.000000,...,-0.008563,0.011512,0.122023,0.117113,0.073111,0.056670,0.102740,0.994263,0.994196,0.993582
type1_y,0.983236,0.023511,0.023440,0.013563,0.076608,0.912952,0.930371,0.799922,1.000000,1.000000,...,-0.008563,0.011512,0.122023,0.117113,0.073111,0.056670,0.102740,0.994263,0.994196,0.993582
q1,0.939159,0.000087,-0.003627,0.020889,0.084518,0.828601,0.924039,0.713944,0.965501,0.965501,...,0.012771,0.015312,0.071683,0.116092,0.057620,0.017989,0.063087,0.956817,0.955237,0.954913
q3,0.958128,0.030948,0.031084,-0.003275,0.071565,0.893347,0.902994,0.793332,0.976655,0.976655,...,-0.012309,0.009112,0.124313,0.111599,0.090795,0.068826,0.128285,0.969302,0.970548,0.969334
q4_a,0.865754,0.017028,0.017785,-0.031845,0.051501,0.844919,0.777734,0.777258,0.873901,0.873901,...,0.002412,0.029674,0.187142,0.156415,0.076590,0.138497,0.194197,0.872417,0.870594,0.868434
q5_1,0.704701,0.006928,0.014769,0.021967,0.000386,0.592341,0.687080,0.580509,0.709992,0.709992,...,-0.027765,-0.014921,0.016281,0.091287,0.271621,0.002216,0.033793,0.710495,0.705966,0.705012
q7,0.743690,-0.017192,-0.031877,0.035902,0.104704,0.632550,0.761659,0.542246,0.775438,0.775438,...,0.029169,0.022747,0.003710,0.045175,0.007850,-0.006086,0.011789,0.762660,0.767358,0.769873
q8,0.957782,0.028269,0.030312,0.025881,0.055153,0.937421,0.867711,0.833068,0.963793,0.963793,...,0.002716,0.003205,0.162667,0.125735,0.066535,0.082734,0.119967,0.961286,0.960686,0.959805
q8_1,0.729138,-0.003399,-0.009852,-0.014972,0.100494,0.564933,0.788473,0.461363,0.770109,0.770109,...,-0.027752,0.030303,-0.006918,0.061421,0.056792,-0.033717,-0.009286,0.756391,0.757098,0.758218
q8_2,0.200883,0.030902,0.004949,0.008388,0.029572,0.157432,0.134383,0.175127,0.183294,0.183294,...,-0.013181,0.094859,-0.025278,-0.013105,0.186895,-0.063911,0.022499,0.192697,0.182435,0.183951
q8_3,0.098163,0.081759,0.072918,0.024186,-0.010037,0.066411,0.049410,0.173697,0.085424,0.085424,...,-0.018169,0.020727,-0.032692,-0.007501,0.038629,-0.035739,0.000388,0.090499,0.094354,0.088359
q8_4,0.017274,-0.054663,-0.056042,-0.005301,0.066006,0.004665,-0.023456,0.032038,0.001837,0.001837,...,-0.024499,-0.011619,0.060313,-0.004967,0.038255,-0.032757,-0.014399,0.007206,0.013883,0.007042
q8_5,0.056607,-0.082249,-0.080534,-0.060913,0.054907,0.022918,-0.007327,0.072107,0.041384,0.041384,...,-0.021551,-0.010221,0.111514,-0.004369,-0.010956,0.083171,0.107668,0.048968,0.050408,0.048122
q8_6,-0.032503,-0.053546,-0.047812,-0.006556,-0.040882,-0.029789,-0.053787,-0.028396,-0.037634,-0.037634,...,-0.025446,-0.012069,-0.029386,-0.005159,0.045278,-0.034024,-0.014956,-0.037271,-0.030129,-0.038850
q8_7,0.027226,-0.024909,-0.020879,-0.074595,0.005688,0.001261,0.031443,0.001939,0.021595,0.021595,...,-0.017409,-0.008257,-0.020105,-0.003529,-0.008851,0.127499,-0.010233,0.025604,0.024704,0.028692
q10_1,0.949997,-0.009434,-0.010214,0.044633,0.084762,0.828821,0.894382,0.697245,0.951786,0.951786,...,-0.006338,0.028543,0.076798,0.143092,0.088286,-0.030830,0.007007,0.954255,0.950487,0.952364
q10_2,0.806136,-0.017266,-0.024984,0.044258,0.090024,0.720351,0.744037,0.596834,0.795486,0.795486,...,0.007040,0.042832,0.097448,0.044074,0.130314,-0.006020,-0.024731,0.796634,0.802589,0.806593
q10_3,0.987614,0.017281,0.016378,0.020447,0.082784,0.909602,0.917452,0.803606,0.992509,0.992509,...,-0.010525,0.022777,0.120540,0.122772,0.087864,0.042299,0.083355,0.991975,0.990865,0.991187
q10_4,0.780313,-0.033508,-0.034724,0.025881,0.086332,0.626705,0.796467,0.537590,0.806283,0.806283,...,0.035756,0.036103,-0.024932,0.130351,0.047215,-0.044270,0.000992,0.798897,0.794317,0.794056
q10_5,0.986832,0.031533,0.030391,0.016332,0.079600,0.923418,0.906015,0.818586,0.990234,0.990234,...,-0.007477,0.013723,0.148356,0.140688,0.091508,0.059901,0.112397,0.990278,0.989010,0.989179
q10_6,0.701366,0.035141,0.028620,0.043838,0.071441,0.736655,0.628000,0.674971,0.689960,0.689960,...,0.038349,-0.035069,0.140134,-0.023733,0.177524,0.095447,0.019254,0.689466,0.702325,0.703825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
q6_5_8,0.046760,0.077125,0.080140,0.006519,0.019215,0.006921,0.001071,0.062128,0.024548,0.024548,...,-0.009441,-0.004478,-0.010903,-0.001914,-0.004800,-0.012624,-0.005549,0.036848,0.029716,0.029758
q6_5_9,0.023490,0.003647,0.006354,-0.065595,-0.010250,0.004764,-0.007219,0.037729,0.019506,0.019506,...,0.051380,-0.005185,0.120222,-0.002216,0.089479,-0.014617,-0.006425,0.020549,0.019779,0.018382
q6_5_10,0.120907,-0.012257,-0.052684,0.050013,0.006419,0.152521,0.071085,0.131018,0.119468,0.119468,...,0.071756,-0.015707,0.129446,-0.006714,-0.016837,-0.006038,0.062723,0.120103,0.115320,0.116276
q6_5_11,0.029875,-0.002593,0.001395,-0.007670,-0.021266,0.042507,0.017479,0.057663,0.042653,0.042653,...,-0.016404,-0.007780,-0.018944,-0.003326,0.080791,-0.021934,-0.009642,0.035460,0.036540,0.035944
q6_5_12,0.020776,-0.051372,-0.049168,-0.007081,-0.005767,0.039431,-0.010920,-0.027399,0.019506,0.019506,...,-0.010932,-0.005185,-0.012624,-0.002216,-0.005558,-0.014617,-0.006425,0.017649,0.024168,0.024228
q6_5_13,0.167034,-0.020743,-0.020480,0.001047,-0.001822,0.121613,0.150303,0.139422,0.166485,0.166485,...,0.181169,-0.014029,-0.023946,-0.005997,0.014183,-0.011603,-0.017385,0.170734,0.153373,0.152991
q6_6_1,0.893451,-0.006018,-0.007575,0.094317,0.064001,0.779021,0.871178,0.642752,0.905750,0.905750,...,-0.008673,0.025312,-0.023847,0.079643,0.074743,-0.050443,0.009351,0.902240,0.902834,0.903472
q6_6_2,0.880333,0.038235,0.042330,0.070130,0.051003,0.845477,0.832405,0.721434,0.897741,0.897741,...,-0.029472,-0.008352,-0.013040,0.096325,0.036974,0.027365,0.084044,0.887518,0.890956,0.892654
q6_6_3,0.698423,0.043225,0.047444,0.076890,0.082263,0.608391,0.621490,0.583742,0.659123,0.659123,...,-0.051085,0.005491,0.042151,0.067218,0.147213,-0.033137,-0.030026,0.680235,0.675758,0.678790
q6_6_4,0.563177,0.008947,0.006773,0.005843,0.037243,0.500296,0.626302,0.368110,0.606378,0.606378,...,0.045097,-0.022294,-0.018582,-0.009530,-0.011127,-0.001786,-0.027629,0.583537,0.596149,0.597645
q6_6_5,0.255003,-0.023047,-0.040681,-0.067628,0.107134,0.201253,0.162401,0.203868,0.229198,0.229198,...,-0.043725,0.061282,0.113973,0.149936,-0.017704,-0.030333,-0.036164,0.244223,0.236498,0.238396
q6_6_6,0.611706,-0.062693,-0.072634,-0.020457,0.170983,0.509376,0.542807,0.396503,0.613703,0.613703,...,-0.050972,-0.004812,0.109320,0.091055,-0.034994,-0.020390,0.012033,0.620372,0.610153,0.612411
q6_6_7,0.035723,0.034020,0.026315,-0.076986,0.009044,0.050634,0.036279,0.048118,0.036667,0.036667,...,-0.018175,-0.008620,0.057893,-0.003685,-0.009240,0.083636,-0.010683,0.039504,0.034622,0.039066
q6_6_8,0.231802,0.078464,0.078675,-0.051195,-0.045028,0.365803,0.201155,0.353455,0.250362,0.250362,...,-0.005545,-0.019285,0.090300,-0.008243,-0.020672,0.090761,0.099942,0.236949,0.248623,0.244832
q6_6_9,0.163611,-0.022302,-0.022061,-0.090810,-0.055453,0.245485,0.107132,0.263191,0.157612,0.157612,...,-0.049004,-0.028203,0.215699,-0.012056,-0.030232,0.057825,0.124920,0.163301,0.161134,0.158973
q6_6_10,0.056703,0.022071,0.027262,-0.025623,-0.001669,0.012754,0.079930,0.082178,0.056644,0.056644,...,-0.020394,-0.009672,-0.023552,-0.004135,-0.010368,0.138607,-0.011987,0.057981,0.054698,0.057763
q6_6_11,0.715561,-0.028910,-0.022619,-0.026206,0.075861,0.559530,0.738749,0.468883,0.735664,0.735664,...,-0.000462,-0.012711,0.228755,-0.005433,-0.013625,0.012188,-0.015752,0.738589,0.734087,0.735518
q6_6_12,-0.011631,0.055528,0.061014,-0.056273,-0.082260,0.004835,-0.005073,-0.020476,-0.006380,-0.006380,...,0.021077,-0.009652,-0.023501,-0.004126,0.179206,0.003004,-0.011961,-0.005906,-0.010837,-0.011638
q6_6_13,0.045046,0.033561,0.034167,-0.062744,-0.021312,0.041719,0.027857,0.080322,0.053663,0.053663,...,-0.018062,-0.008567,-0.020859,-0.003662,0.097881,-0.007086,-0.010616,0.047894,0.048612,0.048701
q6_6_14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
q6_6_15,-0.013952,-0.010009,-0.011934,0.018693,-0.065653,-0.030875,-0.021570,0.019461,-0.008563,-0.008563,...,1.000000,-0.013512,0.039228,-0.005776,0.026796,0.001385,-0.016746,-0.011328,-0.015172,-0.016203
q6_6_16,0.015025,-0.018878,-0.015746,-0.017495,-0.011086,-0.002528,-0.016672,0.037225,0.011512,0.011512,...,-0.013512,1.000000,-0.015604,-0.002739,-0.006870,-0.018067,-0.007942,0.009523,0.012824,0.015496
q6_6_17,0.156450,-0.002471,0.003014,-0.118221,0.086420,0.150777,0.095528,0.183303,0.122023,0.122023,...,0.039228,-0.015604,1.000000,-0.006670,-0.016727,0.103303,0.133284,0.145111,0.141828,0.144301
q6_6_18,0.113497,-0.014017,-0.012733,0.001015,0.032479,0.075783,0.084455,0.017153,0.117113,0.117113,...,-0.005776,-0.002739,-0.006670,1.000000,-0.002936,-0.007723,-0.003395,0.113534,0.103203,0.103137
q6_6_19,0.079809,0.072504,0.076710,-0.036219,-0.034368,0.037891,0.115472,0.123206,0.073111,0.073111,...,0.026796,-0.006870,-0.016727,-0.002936,1.000000,-0.019367,-0.008513,0.071422,0.071757,0.068889
q6_6_20,0.045742,0.105764,0.104775,-0.085987,-0.022936,0.086612,0.045520,0.102503,0.056670,0.056670,...,0.001385,-0.018067,0.103303,-0.007723,-0.019367,1.000000,0.186450,0.049096,0.058265,0.057574
q6_6_21,0.101527,0.098794,0.103793,-0.063707,-0.001968,0.131207,0.078295,0.179054,0.102740,0.102740,...,-0.016746,-0.007942,0.133284,-0.003395,-0.008513,0.186450,1.000000,0.098863,0.110971,0.103521
q6_7,0.995513,0.024999,0.024951,0.011181,0.086076,0.908396,0.919270,0.799020,0.994263,0.994263,...,-0.011328,0.009523,0.145111,0.113534,0.071422,0.049096,0.098863,1.000000,0.996830,0.996999
q6_8,0.993762,0.024070,0.023783,0.011640,0.083145,0.915041,0.919591,0.804382,0.994196,0.994196,...,-0.015172,0.012824,0.141828,0.103203,0.071757,0.058265,0.110971,0.996830,1.000000,0.998019
q6_9,0.994018,0.024020,0.023438,0.012231,0.086233,0.912728,0.919351,0.802323,0.993582,0.993582,...,-0.016203,0.015496,0.144301,0.103137,0.068889,0.057574,0.103521,0.996999,0.998019,1.000000

In [101]:
# corrDF999.to_csv("./dataset/result_Corr.csv")

## K-Means Clustering

In [102]:
import pandas as pd
# K-Means 라이브러리
from sklearn.cluster import KMeans
# 시각화 라이브러리
import matplotlib.pyplot as plt

# Only needed if you want to display your plots inline if using Notebook
# change inline to auto if you have Spyder installed
%matplotlib inline

In [132]:
### 특성정보 분리
# "q1", #당일/숙박여행 여부
# "q3", #여행 주 목적
# "q4_a", #정보획득지
# "q5_1", #여행 일행수
# "q8", #사전예약
# "sex",
# "job_group",
# "q7_grade",
# "q6_3_a", #여행지 선택이유
# "q6_3_b",
# "q6_3_c",
# "q6_4" # 주요 이동수단
            
features = result01[["q1","q3","q4_a","q5_1","q6_4","q7","q7_grade", "q8","q10_grade"]]

In [133]:
### 모델선언 및 feature 만 활용하여 자율학습
model = KMeans(n_clusters=2, algorithm="auto")
model.fit(features)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [134]:
predict = pd.DataFrame(model.predict(features))
predict.columns=["cluster"]

In [135]:
testDF = pd.concat([result01, predict], sort = False, axis=1)

In [137]:
testDF

,hid,pid,sex,age,sido,occ1,age_group,type1_x,month,q1,...,q6_6_19,q6_6_20,q6_6_21,q6_7,q6_8,q6_9,job_group,q10_grade,q7_grade,cluster
0,10003,1000303,2,28,1,16,20,1.0,4.0,2.0,...,NaN,NaN,NaN,4.0,4.0,3.0,3,61.20,4,1
1,10019,1001904,2,23,1,14,20,1.0,4.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,3,0
2,10019,1001904,2,23,1,14,20,1.0,8.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,3,0
3,10031,1003105,1,21,1,14,20,1.0,3.0,2.0,...,NaN,NaN,NaN,5.0,5.0,5.0,1,89.20,2,0
4,10031,1003105,1,21,1,14,20,1.0,10.0,2.0,...,NaN,NaN,NaN,5.0,4.0,5.0,1,86.08,2,0
5,10031,1003105,1,21,1,14,20,1.0,10.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,68.08,2,0
6,10031,1003105,1,21,1,14,20,1.0,10.0,2.0,...,NaN,NaN,NaN,5.0,4.0,5.0,1,84.52,2,0
7,10031,1003105,1,21,1,14,20,1.0,10.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,66.52,2,0
8,10045,1004503,2,22,1,14,20,1.0,4.0,2.0,...,NaN,NaN,NaN,4.0,5.0,4.0,1,68.08,3,0
9,10045,1004503,2,22,1,14,20,1.0,6.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,62.44,3,0
10,10045,1004503,2,22,1,14,20,1.0,8.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,60.64,1,0
11,10056,1005604,2,23,1,14,20,1.0,5.0,2.0,...,NaN,NaN,NaN,5.0,5.0,5.0,1,89.20,2,0
12,10062,1006204,2,24,1,14,20,1.0,2.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,5,1
13,10062,1006204,2,24,1,14,20,1.0,8.0,1.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,2,0
14,10062,1006204,2,24,1,14,20,1.0,8.0,1.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,3,0
15,10062,1006204,2,24,1,14,20,1.0,8.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,2,0
16,10062,1006204,2,24,1,14,20,1.0,8.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,3,0
17,10062,1006204,2,24,1,14,20,1.0,9.0,1.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,2,0
18,10062,1006205,1,23,1,15,20,1.0,1.0,2.0,...,NaN,NaN,NaN,3.0,4.0,3.0,1,47.48,3,0
19,10062,1006205,1,23,1,15,20,1.0,5.0,1.0,...,NaN,NaN,NaN,3.0,3.0,3.0,1,37.44,4,0
20,10062,1006205,1,23,1,15,20,1.0,9.0,2.0,...,NaN,NaN,NaN,4.0,3.0,3.0,1,55.60,5,1
21,10062,1006205,1,23,1,15,20,1.0,9.0,2.0,...,NaN,NaN,NaN,3.0,3.0,3.0,1,44.40,5,1
22,10062,1006205,1,23,1,15,20,1.0,9.0,2.0,...,NaN,NaN,NaN,5.0,5.0,4.0,1,85.60,4,1
23,10086,1008604,1,29,1,5,20,1.0,8.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,2,64.00,4,1
24,10113,1011304,2,25,1,14,20,1.0,1.0,1.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,61.48,2,0
25,10113,1011304,2,25,1,14,20,1.0,4.0,1.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,60.64,3,0
26,10139,1013903,1,20,8,14,20,1.0,7.0,2.0,...,NaN,NaN,NaN,5.0,4.0,4.0,1,77.56,3,0
27,10139,1013903,1,20,8,14,20,1.0,7.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,63.16,3,0
28,10142,1014204,2,26,1,14,20,1.0,10.0,2.0,...,NaN,NaN,NaN,4.0,4.0,5.0,1,69.40,2,0
29,10146,1014603,2,29,1,3,20,1.0,5.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,2,64.00,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290,15257,1525704,1,29,8,14,20,1.0,8.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,61.48,1,0
1291,15259,1525903,2,22,8,14,20,1.0,3.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,59.44,2,0
1292,15259,1525903,2,22,8,14,20,1.0,6.0,2.0,...,NaN,NaN,NaN,4.0,5.0,5.0,1,72.52,2,0
1293,15259,1525903,2,22,8,14,20,1.0,12.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,65.68,3,0
1294,15259,1525904,1,20,8,14,20,1.0,6.0,1.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,59.92,3,0
1295,15265,1526503,1,20,8,14,20,1.0,12.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,65.68,3,1
1296,15283,1528303,2,21,8,14,20,1.0,2.0,1.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,64.00,1,0
1297,15294,1529403,1,25,8,14,20,1.0,8.0,1.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,64.00,3,0
1298,15296,1529603,2,26,8,3,20,1.0,5.0,1.0,...,NaN,NaN,NaN,4.0,3.0,4.0,2,52.76,4,0
1299,15296,1529603,2,26,8,3,20,1.0,8.0,2.0,...,NaN,NaN,NaN,5.0,5.0,5.0,2,91.72,2,0
1300,15296,1529603,2,26,8,3,20,1.0,10.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,2,70.00,3,0
1301,15324,1532404,2,20,8,14,20,1.0,2.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,61.48,2,0
1302,15324,1532404,2,20,8,14,20,1.0,4.0,2.0,...,NaN,20.0,NaN,3.0,3.0,3.0,1,36.00,1,0
1303,15327,1532703,2,25,8,14,20,1.0,5.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,60.88,4,1
1304,15331,1533103,1,25,10,10,20,1.0,11.0,1.0,...,NaN,NaN,NaN,3.0,3.0,3.0,4,37.08,3,0
1305,15331,1533103,1,25,10,10,20,1.0,12.0,2.0,...,NaN,NaN,NaN,3.0,3.0,3.0,4,44.40,3,0
1306,15331,1533104,1,22,10,8,20,1.0,12.0,1.0,...,NaN,NaN,NaN,4.0,4.0,3.0,2,55.32,2,0
1307,15348,1534803,2,21,11,14,20,1.0,10.0,1.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,59.08,4,0
1308,15348,1534803,2,21,11,14,20,1.0,12.0,2.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,63.16,3,0
1309,15370,1537003,2,21,12,14,20,1.0,5.0,2.0,...,NaN,NaN,NaN,5.0,4.0,4.0,1,76.84,3,0
1310,15380,1538003,1,26,15,14,20,1.0,2.0,2.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,59.92,4,1
1311,15380,1538003,1,26,15,14,20,1.0,2.0,2.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,59.92,5,1
1312,15380,1538003,1,26,15,14,20,1.0,2.0,1.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,62.92,2,0
1313,15380,1538003,1,26,15,14,20,1.0,2.0,1.0,...,NaN,NaN,NaN,4.0,4.0,4.0,1,62.92,3,0
1314,15380,1538003,1,26,15,14,20,1.0,4.0,2.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,57.88,4,1
1315,15380,1538003,1,26,15,14,20,1.0,6.0,2.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,58.36,4,1
1316,15380,1538003,1,26,15,14,20,1.0,10.0,2.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,56.32,3,1
1317,15380,1538004,1,23,15,14,20,1.0,8.0,1.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,60.40,3,0
1318,15380,1538004,1,23,15,14,20,1.0,10.0,1.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,61.24,3,0
1319,15380,1538004,1,23,15,14,20,1.0,12.0,1.0,...,NaN,20.0,NaN,4.0,4.0,4.0,1,56.32,4,0

In [139]:
tmp2 = testDF.groupby(["job_group", "cluster"]).mean()[["q1","q3","q4_a","q5_1","q6_4","q7_grade", "q8","q10_grade"]]
tmp2

                         q1        q3      q4_a      q5_1      q6_4  q7_grade  \
job_group cluster
1         0        1.409524  1.050340  4.156463  4.604082  3.687075  2.223129
          1        1.977273  1.000000  3.715909  4.000000  2.420455  3.954545
2         0        1.476038  1.025559  3.747604  3.907348  2.440895  2.201278
          1        1.876923  1.000000  3.415385  2.923077  1.800000  4.000000
3         0        1.181818  1.000000  3.236364  5.090909  4.400000  1.890909
          1        1.846154  1.000000  3.076923  4.461538  3.153846  4.461538
4         0        1.294118  1.000000  4.264706  3.235294  3.500000  1.823529
          1        2.000000  1.000000  2.750000  4.250000  3.000000  3.500000
999       0        1.181818  1.181818  4.181818  3.454545  2.363636  2.818182
          1        2.000000  1.000000  4.000000  2.000000  3.000000  4.000000

                         q8  q10_grade
job_group cluster
1         0        1.745578  65.876027
          1        1.352273  64.988182
2         0        1.626198  65.685751
          1        1.400000  65.561846
3         0        1.818182  69.252364
          1        1.307692  72.101538
4         0        1.705882  65.820000
          1        1.000000  74.800000
999       0        2.000000  69.160000
          1        1.000000  89.200000

In [131]:
testDF.to_csv("../dataset/result_cluster.csv")

## Decision Tree

In [44]:
def decisionTreeRegressor(dataName, features, label):
    from sklearn import datasets, tree
    from sklearn.metrics import mean_squared_error
    from sklearn.metrics import mean_absolute_error
    from sklearn.metrics import r2_score
    from sklearn.linear_model import LinearRegression
    from pandas.compat import StringIO
    from sklearn.tree import DecisionTreeClassifier, export_graphviz
    
    trainingData_features = dataName[dataName.index%4 != 0][features]
    trainingData_label = dataName[dataName.index%4 != 0][label]
    testData_features = dataName[dataName.index%4 == 0][features]
    testData_label = dataName[dataName.index%4 == 0]

    model_method = tree.DecisionTreeRegressor()
    model = model_method.fit(trainingData_features, trainingData_label)
    decisionTreeRegressor = model.predict(testData_features)

    decisionTreeRegressor = pd.DataFrame(decisionTreeRegressor)
    decisionTreeRegressor.columns = ["PREDICT"]
    decisionTreeRegressorResult = pd.concat([testData_label.reset_index(drop=True), decisionTreeRegressor], axis=1)

    print("MAE : {:.2f}".format(mean_absolute_error(testData_label.reset_index()[label], decisionTreeRegressorResult["PREDICT"])))
    print("MSE : {:.2f}".format(mean_squared_error(testData_label.reset_index()[label], decisionTreeRegressorResult["PREDICT"])))
    print("RMSE : {:.2f}".format(math.sqrt(mean_squared_error(testData_label.reset_index()[label], decisionTreeRegressorResult["PREDICT"]))))
    print("R2 : {:.2f}".format(r2_score(testData_label[label], decisionTreeRegressorResult['PREDICT'])))

    dot_data = StringIO()
    export_graphviz(model, out_file=dot_data, 
                    rounded=True,
                    feature_names = features,
                    filled=True,
                    impurity=False,
                    node_ids=True,
                    proportion=True,
                    special_characters=False)
    graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
    return Image(graph.create_png())

In [45]:
# feature 값을 지정
# job_group 직업분류 1.학생 2.직장인 3.무직 4.군인 999.기타
# q1 당일/숙박여행여부
# q3 여행목적
# q4_a, q4_b, q4_c 정보획득지
# q6_3_a, q6_3_b, q6_3_a 여행지 선택이유
# q7_grade 소비등급
# q8 사전예약여부
# q10_grade 만족도

features = ["q4_a","q7_grade"]
label = ["q10_grade"]

### 1-1. 학생 그룹

In [46]:
studentDF = testDF[testDF["job_group"] == 1]

In [47]:
decisionTreeRegressor(studentDF,features,label)

MAE : 9.83
MSE : 187.31
RMSE : 13.69
R2 : -0.08

NameError: name 'pydotplus' is not defined

### 1-2. 직장인 그룹

In [ ]:
workerDF = testDF[testDF["job_group"] == 2]

In [ ]:
decisionTreeRegressor(workerDF,features,label)

### 연습장

In [ ]:
# 만족도 65이상의 데이터만 필터
filter = 65

targetDF = testDF[testDF["q10_grade"] > filter]

In [ ]:
groupKey = ["job_group","cluster","q7_grade"]

In [ ]:
tmp = testDF.groupby(groupKey).mean()[["q10_grade"]]

In [ ]:
tmp

In [ ]:
tmp2 = targetDF.groupby(groupKey).count()[["q6_6_1","q6_6_2","q6_6_3","q6_6_4","q6_6_5","q6_6_6","q6_6_7","q6_6_8","q6_6_9","q6_6_10"
                                            ,"q6_6_11","q6_6_12","q6_6_13","q6_6_14","q6_6_15","q6_6_16","q6_6_17","q6_6_18","q6_6_19","q6_6_20"
                                            ,"q6_6_21"]]

In [ ]:
tmp2.columns = ["자연/풍경 감상","음식관광","야외 위락 및 스포츠활동","역사유적지","테마파크","휴식/휴양","온천/스파","쇼핑",
                "지역문화예술/공연/전시시설","스포츠관람","지역 축제","교육/체험프로그램","종교/성지순례","갬블링","시티투어",
                "드라마 촬영지","가족/친지/친구 방문","회의참가/시찰","교육/훈련/연수","유흥/오락","기타"]

In [ ]:
#여행지 활동
tmp2

In [ ]:
tmp3 = targetDF.groupby(groupKey).count()[["q6_5_1","q6_5_2","q6_5_3","q6_5_4","q6_5_5","q6_5_6","q6_5_7",
                                          "q6_5_8","q6_5_9","q6_5_10","q6_5_11","q6_5_12","q6_5_13"]]

In [ ]:
# 숙박시설
tmp3.columns = ["숙박X","호텔","콘도","유스호스텔","모텔/여관","펜션","민박","야영","자연휴양림","가족/친지집",
                "연수원/수련원","전통한옥","기타"]

In [ ]:
tmp3

In [ ]:
tmp4 = targetDF.groupby(groupKey).count()[["q6_3_a","q6_3_b","q6_3_c"]]

In [ ]:
# 여행지 선택이유
tmp3.columns = ["숙박X","호텔","콘도","유스호스텔","모텔/여관","펜션","민박","야영","자연휴양림","가족/친지집",
                "연수원/수련원","전통한옥","기타"]

In [ ]:
testDF["q6_3_b"] = testDF["q6_3_b"].fillna(0)
testDF["q6_3_c"] = testDF["q6_3_c"].fillna(0)

In [ ]:
tempList0000 = []

for i in range(0,len(testDF)):
    tempList2222 = []
    
    q6_3_1 = testDF.loc[i,"q6_3_a"]
    q6_3_2 = testDF.loc[i,"q6_3_b"]
    q6_3_3 = testDF.loc[i,"q6_3_c"]
    
    for j in range(0,15):
        if (q6_3_1 == j):
            tempList2222.append(q6_3_1)
        elif (q6_3_2 == j):
            tempList2222.append(q6_3_2)
        elif (q6_3_3 == j):
            tempList2222.append(q6_3_3)  
        else:
            tempList2222.append(0)
    tempList0000.append(tempList2222)

In [ ]:
tempDF = pd.DataFrame(tempList0000)
tempDF.columns = ["q6_3 : 지명도","q6_3 : 볼거리","q6_3 : 여행경비","q6_3 : 이동거리","q6_3 : 시간","q6_3 : 숙박시설","q6_3 : 동반자 유형",
          "q6_3 : 쇼핑","q6_3 : 음식","q6_3 : 교통편","q6_3 : 체험프로그램","q6_3 : 경험자 추천","q6_3 : 관광지 편의시설",
           "q6_3 : 교육성","q6_3 : 기타"]
# result01 = pd.concat([testDF, tempList0000], axis=1)

In [ ]:
testDF["q4_b"] = testDF["q4_b"].fillna(0)

In [ ]:
tempList0000 = []

for i in range(0,len(testDF)):
    tempList2222 = []
    
    q4_a = testDF.loc[i,"q4_a"]
    q4_b = testDF.loc[i,"q4_b"]
    
    for j in range(0,11):
        if (q4_a == j):
            tempList2222.append(q4_a)
        elif (q4_b == j):
            tempList2222.append(q4_b) 
        else:
            tempList2222.append(0)
    tempList0000.append(tempList2222)

In [ ]:
tempDF = pd.DataFrame(tempList0000)
tempDF.columns = ["q4_ab : 여행사","q4_ab : 가족/친지","q4_ab : 친구/동료","q4_ab : 인터넷","q4_ab : 관광서적","q4_ab : 기사/방송",
                 "q4_ab : 광고","q4_ab : 과거경험","q4_ab : 모바일앱","q4_ab : 기타","q4_ab : 없음"]
# result01 = pd.concat([testDF, tempList0000], axis=1)