In [7]:
import pandas as pd
import requests
from pandas.io.json import json_normalize

In [8]:
url='http://kosis.kr/openapi/statisticsData.do?method=getList&apiKey=ZmY2Yzg3OTY1ODQ3Y2FlMDE4MDVkZTMyN2MxM2ZjMjA=&format=json&jsonVD=Y&userStatsId=botopia/116/TX_116110032/2/1/20190418174241&prdSe=Y&newEstPrdCnt=1'
response = requests.get(url)
response

In [9]:
json = response.json()

In [10]:
df = json_normalize(json)
df.head()

,C1,C1_NM,C1_NM_ENG,C1_OBJ_NM,C1_OBJ_NM_ENG,C2,C2_NM,C2_NM_ENG,C2_OBJ_NM,DT,ITM_ID,ITM_NM,ORG_ID,PRD_DE,PRD_SE,TBL_ID,TBL_NM,UNIT_NM,UNIT_NM_ENG
0,1511613102251770A.00,계,Total,시도별,Metropolitan city and province,1511613102251770B.0,계,Total,면적별,6460489,1611613103251770T1,동수,116,2007,A,TX_116110032,건축물 현황(면적별시도별),동,Building
1,1511613102251770A.00,계,Total,시도별,Metropolitan city and province,1511613102251770B.2,1백㎡미만,NaN,면적별,3231739,1611613103251770T1,동수,116,2007,A,TX_116110032,건축물 현황(면적별시도별),동,Building
2,1511613102251770A.00,계,Total,시도별,Metropolitan city and province,1511613102251770B.3,1백㎡~2백㎡미만,NaN,면적별,1485260,1611613103251770T1,동수,116,2007,A,TX_116110032,건축물 현황(면적별시도별),동,Building
3,1511613102251770A.00,계,Total,시도별,Metropolitan city and province,1511613102251770B.4,2백㎡~3백㎡미만,NaN,면적별,467129,1611613103251770T1,동수,116,2007,A,TX_116110032,건축물 현황(면적별시도별),동,Building
4,1511613102251770A.00,계,Total,시도별,Metropolitan city and province,1511613102251770B.5,3백㎡~5백㎡미만,NaN,면적별,557924,1611613103251770T1,동수,116,2007,A,TX_116110032,건축물 현황(면적별시도별),동,Building

In [12]:
df.to_csv("./건축물 현황(면적별,시도별).csv", encoding='ms949')