In [1]:
import pandas as pd

# 1.  데이터 로드

In [2]:
selloutData = pd.read_csv('../dataset2/kopo_channel_seasonality_new.csv')

In [3]:
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK      int64
QTY         float64
dtype: object

### 데이터 타입 통합

In [4]:
selloutData["YEARWEEK"] = selloutData.YEARWEEK.astype("str")
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK     object
QTY         float64
dtype: object

# 2. 행/열 조회

### 음수 (-) 인 판매량 데이터가 관찰됨

In [5]:
selloutData.min()

REGIONID         A00
PRODUCT     PRODUCT1
YEARWEEK      201401
QTY             -364
dtype: object

In [6]:
len(selloutData[selloutData.QTY < 0])

323

In [7]:
selloutData2 = selloutData[selloutData.QTY < 0]

# 3. 데이터 정제

### (-) 값을 0 으로 대체함

In [8]:
import numpy as np

In [9]:
selloutData["NEW_QTY"] = np.where(selloutData.QTY < 0, 0, selloutData.QTY)

In [10]:
selloutData[selloutData.QTY < 0][selloutData.NEW_QTY!=0]

C:\Users\SMART-15\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

Empty DataFrame
Columns: [REGIONID, PRODUCT, YEARWEEK, QTY, NEW_QTY]
Index: []

In [11]:
selloutData[selloutData.QTY > 0][selloutData.QTY != selloutData.NEW_QTY]

C:\Users\SMART-15\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

Empty DataFrame
Columns: [REGIONID, PRODUCT, YEARWEEK, QTY, NEW_QTY]
Index: []

### 연도별 주차수가 다른 Year 가 관찰됨 (53 주차 데이터를 제거)

In [12]:
selloutData.max()

REGIONID            A77
PRODUCT        PRODUCT8
YEARWEEK         201652
QTY         1.66321e+06
NEW_QTY     1.66321e+06
dtype: object

In [13]:
selloutData["YEAR"] = selloutData.YEARWEEK.str[0:4]
selloutData["WEEK"] = selloutData.YEARWEEK.str[4:6]

In [14]:
refinedSelloutData = selloutData[selloutData.WEEK.astype(int) <= 52]

In [15]:
len(selloutData) - len(refinedSelloutData)

794

### 데이터 정렬

In [16]:
sortKey = ["REGIONID", "PRODUCT", "YEARWEEK"]

In [17]:
sortedData = refinedSelloutData.sort_values(sortKey)

### 데이터 집계 (Group By)

In [18]:
groupKey = ["REGIONID", "PRODUCT"]

In [19]:
gfunction = ["mean", "std", "size"]

In [20]:
groupData = sortedData.groupby(groupKey)["NEW_QTY"].agg(gfunction).reset_index()
groupData

    REGIONID    PRODUCT           mean            std  size
0        A00  PRODUCT34     133.057692     155.176039   156
1        A00  PRODUCT58     105.250000     274.315679   156
2        A00  PRODUCT59   35957.570513   15154.625012   156
3        A01   PRODUCT1    5712.775641    3716.549078   156
4        A01  PRODUCT12  196825.403846  199486.717203   156
5        A01  PRODUCT14   17895.333333    9419.908594   156
6        A01  PRODUCT15    4755.391026    1532.289405   156
7        A01  PRODUCT16    1394.519231     736.225916   156
8        A01  PRODUCT19    3339.108974     997.979110   156
9        A01   PRODUCT2   22725.461538   23375.575772   156
10       A01  PRODUCT20      62.929487      75.863639   156
11       A01  PRODUCT33   11902.820513    6317.618260   156
12       A01  PRODUCT34  108119.282051  117646.571047   156
13       A01   PRODUCT4   25874.326923   33010.282181   156
14       A01  PRODUCT47   11004.032051    8269.661534   156
15       A01  PRODUCT56    6297.544872    1838.444080   156
16       A01  PRODUCT57    6808.243590    1394.972523   156
17       A01  PRODUCT58   27251.121795   28156.570449   156
18       A01  PRODUCT59  642026.737179  181141.756075   156
19       A01   PRODUCT6     812.692308    3269.463211   156
20       A01  PRODUCT60       0.923077       2.065191   156
21       A01  PRODUCT62   11342.955128    5732.406958   156
22       A01  PRODUCT63   47631.666667   34676.000829   156
23       A01   PRODUCT7    2075.076923    1305.103850   156
24       A01  PRODUCT75   30082.230769    9327.083324   156
25       A01   PRODUCT8     187.096154     160.986226   156
26       A02   PRODUCT1     153.185897     144.330213   156
27       A02  PRODUCT12    8905.448718    7250.493818   156
28       A02  PRODUCT14    1793.544872     686.521116   156
29       A02  PRODUCT16      23.333333      57.262534   156
..       ...        ...            ...            ...   ...
764      A65   PRODUCT1      62.288462      41.826988   156
765      A65  PRODUCT12    1111.250000     652.922617   156
766      A65  PRODUCT14      16.839744      15.950527   156
767      A65  PRODUCT33     122.134615      55.010039   156
768      A65  PRODUCT34    1776.628205    1528.402177   156
769      A65  PRODUCT40       9.538462      10.240580   156
770      A65  PRODUCT47      23.108974      20.074562   156
771      A65  PRODUCT56      87.897436      28.800130   156
772      A65  PRODUCT57      91.339744      40.052948   156
773      A65  PRODUCT58     180.967949     198.533281   156
774      A65  PRODUCT59   12053.365385    5785.422717   156
775      A65  PRODUCT60      81.884615      25.299742   156
776      A65  PRODUCT62     187.801282      56.827347   156
777      A66  PRODUCT34     177.224359     282.831389   156
778      A66  PRODUCT58       4.814103       8.586414   156
779      A66  PRODUCT59    3776.121795    2207.299659   156
780      A67  PRODUCT34     706.544872     348.450271   156
781      A67  PRODUCT58      40.987179      62.239805   156
782      A67  PRODUCT59   21480.782051    6453.971304   156
783      A68  PRODUCT34     290.570513     179.571681   156
784      A68  PRODUCT58       1.660256       4.263115   156
785      A68  PRODUCT59    7780.173077    5596.191831   156
786      A69  PRODUCT34     166.570513     203.824121   156
787      A69  PRODUCT58       4.506410       5.791536   156
788      A69  PRODUCT59    8274.301282    6077.128909   156
789      A70  PRODUCT34    2166.666667    1484.221748   156
790      A70  PRODUCT58      60.730769      66.921075   156
791      A70  PRODUCT59   69345.288462   35988.802775   156
792      A77   PRODUCT1    2889.333333     943.775645   156
793      A77  PRODUCT12    3471.307692    1692.825844   156

[794 rows x 5 columns]

In [21]:
groupData.rename(columns={"mean" : "MEAN", "std" : "STD"}, inplace = True)

### 데이터 합치기 (Join)

In [22]:
refinedSelloutData.columns

Index(['REGIONID', 'PRODUCT', 'YEARWEEK', 'QTY', 'NEW_QTY', 'YEAR', 'WEEK'], dtype='object')

In [23]:
groupData.columns

Index(['REGIONID', 'PRODUCT', 'MEAN', 'STD', 'size'], dtype='object')

In [24]:
joinKey = ["REGIONID", "PRODUCT"]

In [25]:
joinData = pd.merge(refinedSelloutData, groupData, on=joinKey, how="left")
joinData

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MEAN,STD,size
0,A60,PRODUCT4,201402,71.0,71.0,2014,02,44.487179,33.158366,156
1,A60,PRODUCT59,201402,22275.0,22275.0,2014,02,35359.051282,11371.146466,156
2,A60,PRODUCT34,201402,4463.0,4463.0,2014,02,6122.038462,1630.842988,156
3,A60,PRODUCT47,201402,0.0,0.0,2014,02,0.378205,0.789797,156
4,A60,PRODUCT56,201402,23.0,23.0,2014,02,18.519231,7.437890,156
5,A60,PRODUCT57,201402,14.0,14.0,2014,02,146.455128,70.700946,156
6,A60,PRODUCT12,201402,1186.0,1186.0,2014,02,1211.544872,394.611272,156
7,A60,PRODUCT1,201402,7.0,7.0,2014,02,3.596154,4.148500,156
8,A60,PRODUCT33,201402,101.0,101.0,2014,02,60.647436,17.466209,156
9,A60,PRODUCT62,201402,336.0,336.0,2014,02,327.743590,108.207261,156
10,A37,PRODUCT58,201402,0.0,0.0,2014,02,23.423077,22.437020,156
11,A37,PRODUCT59,201402,11492.0,11492.0,2014,02,25490.487179,11416.026572,156
12,A37,PRODUCT34,201402,825.0,825.0,2014,02,1257.147436,1008.162537,156
13,A31,PRODUCT58,201402,0.0,0.0,2014,02,41.551282,45.350576,156
14,A31,PRODUCT59,201402,560.0,560.0,2014,02,28209.570513,18794.274645,156
15,A31,PRODUCT34,201402,103.0,103.0,2014,02,464.737179,234.272632,156
16,A04,PRODUCT58,201402,0.0,0.0,2014,02,1318.185897,1711.784233,156
17,A04,PRODUCT63,201402,740.0,740.0,2014,02,221.397436,205.039750,156
18,A04,PRODUCT15,201402,394.0,394.0,2014,02,785.115385,1455.445273,156
19,A04,PRODUCT4,201402,2550.0,2550.0,2014,02,980.538462,685.289949,156
20,A04,PRODUCT16,201402,4.0,4.0,2014,02,9.788462,12.725392,156
21,A04,PRODUCT59,201402,36549.0,36549.0,2014,02,99618.730769,32248.388000,156
22,A04,PRODUCT34,201402,4773.0,4773.0,2014,02,9199.448718,3756.333817,156
23,A04,PRODUCT40,201402,146.0,146.0,2014,02,400.448718,613.942724,156
24,A04,PRODUCT47,201402,5.0,5.0,2014,02,4.608974,4.172991,156
25,A04,PRODUCT60,201402,9.0,9.0,2014,02,5.032051,9.104710,156
26,A04,PRODUCT56,201402,109.0,109.0,2014,02,183.128205,208.647340,156
27,A04,PRODUCT57,201402,1195.0,1195.0,2014,02,1230.269231,471.240961,156
28,A04,PRODUCT12,201402,15028.0,15028.0,2014,02,13571.096154,5145.649058,156
29,A04,PRODUCT1,201402,1319.0,1319.0,2014,02,100.282051,325.292500,156
...,...,...,...,...,...,...,...,...,...,...
123834,A16,PRODUCT64,201630,188.0,188.0,2016,30,192.961538,71.673083,156
123835,A16,PRODUCT48,201630,16.0,16.0,2016,30,27.256410,20.736713,156
123836,A16,PRODUCT49,201630,9.0,9.0,2016,30,20.910256,10.434046,156
123837,A16,PRODUCT74,201630,18.0,18.0,2016,30,12.923077,7.514750,156
123838,A16,PRODUCT40,201630,285.0,285.0,2016,30,197.455128,66.958373,156
123839,A16,PRODUCT47,201630,155.0,155.0,2016,30,102.275641,36.246926,156
123840,A16,PRODUCT60,201630,2491.0,2491.0,2016,30,2120.076923,866.526276,156
123841,A16,PRODUCT56,201630,2026.0,2026.0,2016,30,1404.320513,673.014998,156
123842,A16,PRODUCT12,201630,17067.0,17067.0,2016,30,27581.340321,14409.945764,156
123843,A16,PRODUCT1,201630,168.0,168.0,2016,30,1405.275641,1374.451912,156
123844,A16,PRODUCT41,201630,0.0,0.0,2016,30,193.538462,320.261957,156
123845,A16,PRODUCT51,201630,0.0,0.0,2016,30,0.711538,2.097647,156
123846,A16,PRODUCT68,201630,0.0,0.0,2016,30,36.852564,128.905057,156
123847,A16,PRODUCT33,201630,3887.0,3887.0,2016,30,4197.929487,1871.634556,156
123848,A16,PRODUCT14,201630,95.0,95.0,2016,30,162.480769,83.215342,156
123849,A10,PRODUCT2,201630,12570.0,12570.0,2016,30,4900.788462,5084.417244,156
123850,A10,PRODUCT58,201630,4461.0,4461.0,2016,30,3152.256410,4069.346321,156
123851,A10,PRODUCT63,201630,4308.0,4308.0,2016,30,7880.544872,4075.934354,156
123852,A10,PRODUCT15,201630,0.0,0.0,2016,30,31.602564,74.744613,156
123853,A10,PRODUCT4,201630,3012.0,3012.0,2016,30,3746.903846,1821.315592,156
123854,A10,PRODUCT16,201630,231.0,231.0,2016,30,494.897436,270.211319,156
123855,A10,PRODUCT59,201630,231024.0,231024.0,2016,30,169748.762821,53489.388408,156
123856,A10,PRODUCT34,201630,34436.0,34436.0,2016,30,38260.064103,25942.032798,156
123857,A10,PRODUCT40,201630,0.0,0.0,2016,30,2.378205,5.181036,156
123858,A10,PRODUCT47,201630,4.0,4.0,2016,30,5.397436,4.216220,156
123859,A10,PRODUCT60,201630,824.0,824.0,2016,30,730.711538,180.183097,156
123860,A10,PRODUCT56,201630,275.0,275.0,2016,30,182.224359,81.641749,156
123861,A10,PRODUCT61,201630,0.0,0.0,2016,30,0.346154,0.775877,156
123862,A10,PRODUCT12,201630,15021.0,15021.0,2016,30,30364.948718,13128.329344,156
123863,A10,PRODUCT1,201630,568.0,568.0,2016,30,2467.339744,1521.763800,156

In [26]:
reqcolumns = ["REGIONID", "PRODUCT", "YEARWEEK", "YEAR", "WEEK", "NEW_QTY", "MEAN"]

In [27]:
middleResult = joinData[reqcolumns]

# 4. 계절성 지수 산출

In [28]:
middleResult["SEASONALITY"] = np.where(middleResult.MEAN != 0,
                                       middleResult.NEW_QTY/middleResult.MEAN, 
                                       0)

C:\Users\SMART-15\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [29]:
middleResult

,REGIONID,PRODUCT,YEARWEEK,YEAR,WEEK,NEW_QTY,MEAN,SEASONALITY
0,A60,PRODUCT4,201402,2014,02,71.0,44.487179,1.595965
1,A60,PRODUCT59,201402,2014,02,22275.0,35359.051282,0.629966
2,A60,PRODUCT34,201402,2014,02,4463.0,6122.038462,0.729006
3,A60,PRODUCT47,201402,2014,02,0.0,0.378205,0.000000
4,A60,PRODUCT56,201402,2014,02,23.0,18.519231,1.241952
5,A60,PRODUCT57,201402,2014,02,14.0,146.455128,0.095592
6,A60,PRODUCT12,201402,2014,02,1186.0,1211.544872,0.978915
7,A60,PRODUCT1,201402,2014,02,7.0,3.596154,1.946524
8,A60,PRODUCT33,201402,2014,02,101.0,60.647436,1.665363
9,A60,PRODUCT62,201402,2014,02,336.0,327.743590,1.025192
10,A37,PRODUCT58,201402,2014,02,0.0,23.423077,0.000000
11,A37,PRODUCT59,201402,2014,02,11492.0,25490.487179,0.450835
12,A37,PRODUCT34,201402,2014,02,825.0,1257.147436,0.656248
13,A31,PRODUCT58,201402,2014,02,0.0,41.551282,0.000000
14,A31,PRODUCT59,201402,2014,02,560.0,28209.570513,0.019851
15,A31,PRODUCT34,201402,2014,02,103.0,464.737179,0.221631
16,A04,PRODUCT58,201402,2014,02,0.0,1318.185897,0.000000
17,A04,PRODUCT63,201402,2014,02,740.0,221.397436,3.342405
18,A04,PRODUCT15,201402,2014,02,394.0,785.115385,0.501837
19,A04,PRODUCT4,201402,2014,02,2550.0,980.538462,2.600612
20,A04,PRODUCT16,201402,2014,02,4.0,9.788462,0.408644
21,A04,PRODUCT59,201402,2014,02,36549.0,99618.730769,0.366889
22,A04,PRODUCT34,201402,2014,02,4773.0,9199.448718,0.518835
23,A04,PRODUCT40,201402,2014,02,146.0,400.448718,0.364591
24,A04,PRODUCT47,201402,2014,02,5.0,4.608974,1.084840
25,A04,PRODUCT60,201402,2014,02,9.0,5.032051,1.788535
26,A04,PRODUCT56,201402,2014,02,109.0,183.128205,0.595211
27,A04,PRODUCT57,201402,2014,02,1195.0,1230.269231,0.971332
28,A04,PRODUCT12,201402,2014,02,15028.0,13571.096154,1.107353
29,A04,PRODUCT1,201402,2014,02,1319.0,100.282051,13.152902
...,...,...,...,...,...,...,...,...
123834,A16,PRODUCT64,201630,2016,30,188.0,192.961538,0.974287
123835,A16,PRODUCT48,201630,2016,30,16.0,27.256410,0.587018
123836,A16,PRODUCT49,201630,2016,30,9.0,20.910256,0.430411
123837,A16,PRODUCT74,201630,2016,30,18.0,12.923077,1.392857
123838,A16,PRODUCT40,201630,2016,30,285.0,197.455128,1.443366
123839,A16,PRODUCT47,201630,2016,30,155.0,102.275641,1.515512
123840,A16,PRODUCT60,201630,2016,30,2491.0,2120.076923,1.174957
123841,A16,PRODUCT56,201630,2016,30,2026.0,1404.320513,1.442691
123842,A16,PRODUCT12,201630,2016,30,17067.0,27581.340321,0.618788
123843,A16,PRODUCT1,201630,2016,30,168.0,1405.275641,0.119549
123844,A16,PRODUCT41,201630,2016,30,0.0,193.538462,0.000000
123845,A16,PRODUCT51,201630,2016,30,0.0,0.711538,0.000000
123846,A16,PRODUCT68,201630,2016,30,0.0,36.852564,0.000000
123847,A16,PRODUCT33,201630,2016,30,3887.0,4197.929487,0.925933
123848,A16,PRODUCT14,201630,2016,30,95.0,162.480769,0.584685
123849,A10,PRODUCT2,201630,2016,30,12570.0,4900.788462,2.564893
123850,A10,PRODUCT58,201630,2016,30,4461.0,3152.256410,1.415177
123851,A10,PRODUCT63,201630,2016,30,4308.0,7880.544872,0.546663
123852,A10,PRODUCT15,201630,2016,30,0.0,31.602564,0.000000
123853,A10,PRODUCT4,201630,2016,30,3012.0,3746.903846,0.803864
123854,A10,PRODUCT16,201630,2016,30,231.0,494.897436,0.466763
123855,A10,PRODUCT59,201630,2016,30,231024.0,169748.762821,1.360976
123856,A10,PRODUCT34,201630,2016,30,34436.0,38260.064103,0.900051
123857,A10,PRODUCT40,201630,2016,30,0.0,2.378205,0.000000
123858,A10,PRODUCT47,201630,2016,30,4.0,5.397436,0.741093
123859,A10,PRODUCT60,201630,2016,30,824.0,730.711538,1.127668
123860,A10,PRODUCT56,201630,2016,30,275.0,182.224359,1.509129
123861,A10,PRODUCT61,201630,2016,30,0.0,0.346154,0.000000
123862,A10,PRODUCT12,201630,2016,30,15021.0,30364.948718,0.494682
123863,A10,PRODUCT1,201630,2016,30,568.0,2467.339744,0.230207

In [30]:
finalgroupKey = ["REGIONID", "PRODUCT", "WEEK"]

In [31]:
finalResult = middleResult.groupby(finalgroupKey)["SEASONALITY"].agg(["mean"]).reset_index()

In [33]:
finalResult.rename(columns={"mean" : "SEASONALITY"}, inplace = True)
finalResult.head()

  REGIONID    PRODUCT WEEK  SEASONALITY
0      A00  PRODUCT34   01     2.086814
1      A00  PRODUCT34   02     2.234620
2      A00  PRODUCT34   03     1.773667
3      A00  PRODUCT34   04     1.788698
4      A00  PRODUCT34   05     1.513128

In [34]:
# 정렬!

In [36]:
groupKey2 = ["REGIONID","PRODUCT"]

In [38]:
groupData2 = sortedData.groupby(groupKey2)

In [40]:
len(groupData2)

794

In [45]:
# drop_duplicates = distinct
len(sortedData[["REGIONID","PRODUCT"]].drop_duplicates())

794

In [46]:
# 하나만 뽑아서 디버깅 해보기

In [49]:
oneGroup = groupData2.get_group(list(groupData2.groups)[0])

In [61]:
def mafunction(oneGroup, in_window):

    eachData = oneGroup.reset_index(drop=True)
    eachData["MA"] = eachData.NEW_QTY.rolling(window=in_window, center=True, min_periods=1).mean()

    return eachData

In [62]:
WINDOW = 5

In [63]:
mafunction(oneGroup, WINDOW)

    REGIONID    PRODUCT YEARWEEK    QTY  NEW_QTY  YEAR WEEK          MA
0        A00  PRODUCT34   201401  661.0    661.0  2014   01  639.333333
1        A00  PRODUCT34   201402  679.0    679.0  2014   02  612.500000
2        A00  PRODUCT34   201403  578.0    578.0  2014   03  593.200000
3        A00  PRODUCT34   201404  532.0    532.0  2014   04  545.600000
4        A00  PRODUCT34   201405  516.0    516.0  2014   05  491.200000
5        A00  PRODUCT34   201406  423.0    423.0  2014   06  448.400000
6        A00  PRODUCT34   201407  407.0    407.0  2014   07  436.000000
7        A00  PRODUCT34   201408  364.0    364.0  2014   08  440.400000
8        A00  PRODUCT34   201409  470.0    470.0  2014   09  429.600000
9        A00  PRODUCT34   201410  538.0    538.0  2014   10  418.600000
10       A00  PRODUCT34   201411  369.0    369.0  2014   11  416.600000
11       A00  PRODUCT34   201412  352.0    352.0  2014   12  385.000000
12       A00  PRODUCT34   201413  354.0    354.0  2014   13  336.400000
13       A00  PRODUCT34   201414  312.0    312.0  2014   14  319.400000
14       A00  PRODUCT34   201415  295.0    295.0  2014   15  296.400000
15       A00  PRODUCT34   201416  284.0    284.0  2014   16  261.600000
16       A00  PRODUCT34   201417  237.0    237.0  2014   17  231.400000
17       A00  PRODUCT34   201418  180.0    180.0  2014   18  200.400000
18       A00  PRODUCT34   201419  161.0    161.0  2014   19  166.800000
19       A00  PRODUCT34   201420  140.0    140.0  2014   20  139.000000
20       A00  PRODUCT34   201421  116.0    116.0  2014   21  119.600000
21       A00  PRODUCT34   201422   98.0     98.0  2014   22  101.600000
22       A00  PRODUCT34   201423   83.0     83.0  2014   23   86.600000
23       A00  PRODUCT34   201424   71.0     71.0  2014   24   75.400000
24       A00  PRODUCT34   201425   65.0     65.0  2014   25   72.200000
25       A00  PRODUCT34   201426   60.0     60.0  2014   26   85.800000
26       A00  PRODUCT34   201427   82.0     82.0  2014   27  126.400000
27       A00  PRODUCT34   201428  151.0    151.0  2014   28  219.800000
28       A00  PRODUCT34   201429  274.0    274.0  2014   29  297.600000
29       A00  PRODUCT34   201430  532.0    532.0  2014   30  367.800000
..       ...        ...      ...    ...      ...   ...  ...         ...
126      A00  PRODUCT34   201623    7.0      7.0  2016   23    5.800000
127      A00  PRODUCT34   201624    7.0      7.0  2016   24    6.000000
128      A00  PRODUCT34   201625    5.0      5.0  2016   25    5.800000
129      A00  PRODUCT34   201626    7.0      7.0  2016   26    8.200000
130      A00  PRODUCT34   201627    3.0      3.0  2016   27   90.600000
131      A00  PRODUCT34   201628   19.0     19.0  2016   28   90.800000
132      A00  PRODUCT34   201629  419.0    419.0  2016   29   90.800000
133      A00  PRODUCT34   201630    6.0      6.0  2016   30  106.600000
134      A00  PRODUCT34   201631    7.0      7.0  2016   31  103.200000
135      A00  PRODUCT34   201632   82.0     82.0  2016   32   21.000000
136      A00  PRODUCT34   201633    2.0      2.0  2016   33   20.600000
137      A00  PRODUCT34   201634    8.0      8.0  2016   34   19.600000
138      A00  PRODUCT34   201635    4.0      4.0  2016   35    4.200000
139      A00  PRODUCT34   201636    2.0      2.0  2016   36   24.000000
140      A00  PRODUCT34   201637    5.0      5.0  2016   37  134.600000
141      A00  PRODUCT34   201638  101.0    101.0  2016   38  137.200000
142      A00  PRODUCT34   201639  561.0    561.0  2016   39  151.800000
143      A00  PRODUCT34   201640   17.0     17.0  2016   40  152.800000
144      A00  PRODUCT34   201641   75.0     75.0  2016   41  134.800000
145      A00  PRODUCT34   201642   10.0     10.0  2016   42   25.600000
146      A00  PRODUCT34   201643   11.0     11.0  2016   43   25.800000
147      A00  PRODUCT34   201644   15.0     15.0  2016   44   13.600000
148      A00  PRODUCT34   201645   18.0     18.0  2016   45   13.400000
149      A00  PRODUCT34   201646   14.0     14.0  2016   46   14.600000
150      A00  PRODUCT34   201647    9.0      9.0  2016   47   15.400000
151      A00  PRODUCT34   201648   17.0     17.0  2016   48   18.800000
152      A00  PRODUCT34   201649   19.0     19.0  2016   49   30.600000
153      A00  PRODUCT34   201650   35.0     35.0  2016   50   33.200000
154      A00  PRODUCT34   201651   73.0     73.0  2016   51   37.250000
155      A00  PRODUCT34   201652   22.0     22.0  2016   52   43.333333

[156 rows x 8 columns]

In [64]:
groupData2 = sortedData.groupby(groupKey2).apply(mafunction, (WINDOW))

In [65]:
groupData2

                       REGIONID    PRODUCT YEARWEEK      QTY  NEW_QTY  YEAR  \
REGIONID PRODUCT
A00      PRODUCT34 0        A00  PRODUCT34   201401    661.0    661.0  2014
                   1        A00  PRODUCT34   201402    679.0    679.0  2014
                   2        A00  PRODUCT34   201403    578.0    578.0  2014
                   3        A00  PRODUCT34   201404    532.0    532.0  2014
                   4        A00  PRODUCT34   201405    516.0    516.0  2014
                   5        A00  PRODUCT34   201406    423.0    423.0  2014
                   6        A00  PRODUCT34   201407    407.0    407.0  2014
                   7        A00  PRODUCT34   201408    364.0    364.0  2014
                   8        A00  PRODUCT34   201409    470.0    470.0  2014
                   9        A00  PRODUCT34   201410    538.0    538.0  2014
                   10       A00  PRODUCT34   201411    369.0    369.0  2014
                   11       A00  PRODUCT34   201412    352.0    352.0  2014
                   12       A00  PRODUCT34   201413    354.0    354.0  2014
                   13       A00  PRODUCT34   201414    312.0    312.0  2014
                   14       A00  PRODUCT34   201415    295.0    295.0  2014
                   15       A00  PRODUCT34   201416    284.0    284.0  2014
                   16       A00  PRODUCT34   201417    237.0    237.0  2014
                   17       A00  PRODUCT34   201418    180.0    180.0  2014
                   18       A00  PRODUCT34   201419    161.0    161.0  2014
                   19       A00  PRODUCT34   201420    140.0    140.0  2014
                   20       A00  PRODUCT34   201421    116.0    116.0  2014
                   21       A00  PRODUCT34   201422     98.0     98.0  2014
                   22       A00  PRODUCT34   201423     83.0     83.0  2014
                   23       A00  PRODUCT34   201424     71.0     71.0  2014
                   24       A00  PRODUCT34   201425     65.0     65.0  2014
                   25       A00  PRODUCT34   201426     60.0     60.0  2014
                   26       A00  PRODUCT34   201427     82.0     82.0  2014
                   27       A00  PRODUCT34   201428    151.0    151.0  2014
                   28       A00  PRODUCT34   201429    274.0    274.0  2014
                   29       A00  PRODUCT34   201430    532.0    532.0  2014
...                         ...        ...      ...      ...      ...   ...
A77      PRODUCT12 126      A77  PRODUCT12   201623   5348.0   5348.0  2016
                   127      A77  PRODUCT12   201624   3275.0   3275.0  2016
                   128      A77  PRODUCT12   201625   4158.0   4158.0  2016
                   129      A77  PRODUCT12   201626   4815.0   4815.0  2016
                   130      A77  PRODUCT12   201627   3002.0   3002.0  2016
                   131      A77  PRODUCT12   201628   3319.0   3319.0  2016
                   132      A77  PRODUCT12   201629   4200.0   4200.0  2016
                   133      A77  PRODUCT12   201630   7120.0   7120.0  2016
                   134      A77  PRODUCT12   201631   6345.0   6345.0  2016
                   135      A77  PRODUCT12   201632   5863.0   5863.0  2016
                   136      A77  PRODUCT12   201633   4211.0   4211.0  2016
                   137      A77  PRODUCT12   201634   4019.0   4019.0  2016
                   138      A77  PRODUCT12   201635   3624.0   3624.0  2016
                   139      A77  PRODUCT12   201636   3742.0   3742.0  2016
                   140      A77  PRODUCT12   201637   3002.0   3002.0  2016
                   141      A77  PRODUCT12   201638   5583.0   5583.0  2016
                   142      A77  PRODUCT12   201639  14734.0  14734.0  2016
                   143      A77  PRODUCT12   201640   3603.0   3603.0  2016
                   144      A77  PRODUCT12   201641   4010.0   4010.0  2016
                   145      A77  PRODUCT12   201642   4292.0   4292.0  2016
                   146      A77  PRODUCT12   201643   5760.0   5760.0  2016
                   147      A77  PRODUCT12   201644   4109.0   4109.0  2016
                   148      A77  PRODUCT12   201645   4506.0   4506.0  2016
                   149      A77  PRODUCT12   201646   4255.0   4255.0  2016
                   150      A77  PRODUCT12   201647   3574.0   3574.0  2016
                   151      A77  PRODUCT12   201648   4152.0   4152.0  2016
                   152      A77  PRODUCT12   201649   5086.0   5086.0  2016
                   153      A77  PRODUCT12   201650   5846.0   5846.0  2016
                   154      A77  PRODUCT12   201651   4933.0   4933.0  2016
                   155      A77  PRODUCT12   201652   7551.0   7551.0  2016

                       WEEK           MA
REGIONID PRODUCT
A00      PRODUCT34 0     01   639.333333
                   1     02   612.500000
                   2     03   593.200000
                   3     04   545.600000
                   4     05   491.200000
                   5     06   448.400000
                   6     07   436.000000
                   7     08   440.400000
                   8     09   429.600000
                   9     10   418.600000
                   10    11   416.600000
                   11    12   385.000000
                   12    13   336.400000
                   13    14   319.400000
                   14    15   296.400000
                   15    16   261.600000
                   16    17   231.400000
                   17    18   200.400000
                   18    19   166.800000
                   19    20   139.000000
                   20    21   119.600000
                   21    22   101.600000
                   22    23    86.600000
                   23    24    75.400000
                   24    25    72.200000
                   25    26    85.800000
                   26    27   126.400000
                   27    28   219.800000
                   28    29   297.600000
                   29    30   367.800000
...                     ...          ...
A77      PRODUCT12 126   23  4277.400000
                   127   24  4496.600000
                   128   25  4119.600000
                   129   26  3713.800000
                   130   27  3898.800000
                   131   28  4491.200000
                   132   29  4797.200000
                   133   30  5369.400000
                   134   31  5547.800000
                   135   32  5511.600000
                   136   33  4812.400000
                   137   34  4291.800000
                   138   35  3719.600000
                   139   36  3994.000000
                   140   37  6137.000000
                   141   38  6132.800000
                   142   39  6186.400000
                   143   40  6444.400000
                   144   41  6479.800000
                   145   42  4354.800000
                   146   43  4535.400000
                   147   44  4584.400000
                   148   45  4440.800000
                   149   46  4119.200000
                   150   47  4314.600000
                   151   48  4582.600000
                   152   49  4718.200000
                   153   50  5513.600000
                   154   51  5854.000000
                   155   52  6110.000000

[123864 rows x 8 columns]

In [ ]:
###  실제 QTY  설정? 시에는 상한 하한선이 필요하다. 
### 상한선 = 전체QTY평균 + 해당 상품의 표준편차
### 하한선 = 전체QTY평균 - 해당 상품의 표준편차
### 따라서 안정화시장에서는 이 부분을 정제해야 한다. (높거나 작게 책정된 값 조정을 위함)

In [ ]:
finalgroupKey

In [ ]:
seasonMap = finalResult.groupby(finalgroupKey)["SEASONALITY"].agg("mean").to_dict()

In [ ]:
seasonMap

In [70]:
emptyColumns = ["REGIONID","PRODUCT","ITEM","YEARWEEK","QTY"]

In [71]:
emptyDf = pd.DataFrame(columns=emptyColumns)

In [72]:
emptyDf

Empty DataFrame
Columns: [REGIONID, PRODUCT, ITEM, YEARWEEK, QTY]
Index: []

In [69]:
pd.DataFrame([["A00","PRODUCT34","ITEM01","201925",0]])

     0          1       2       3  4
0  A00  PRODUCT34  ITEM01  201925  0