In [1]:
import pandas as pd
import numpy as np

### 1. 데이터 불러오기 / 타입통합

In [3]:
customerData = pd.read_csv("../dataset/customer.csv")

### 2. 특성 선정 / 데이터 분리

In [4]:
from sklearn.model_selection import train_test_split

In [7]:
features = ["deposit", "stock"]
label = ["label"]

In [12]:
train_test_split(customerData[features], test_size = 0.3, random_state = 24)

[          deposit     stock
 9408   1700000000  45000000
 15055  1390000000  77000000
 4773   1520000000  53000000
 4832   1710000000  55000000
 16314  1870000000  67000000
 12973  1640000000  48000000
 16588  1300000000  42000000
 10272  1650000000  46000000
 12098  1940000000  55000000
 10325  1500000000  35000000
 3935   1260000000  61000000
 4105   1370000000  68000000
 9909   1640000000  76000000
 18438  1230000000  74000000
 4416   1210000000  42000000
 13225  1440000000  72000000
 225    1990000000  58000000
 13479  1320000000  71000000
 18445  2000000000  58000000
 14061  1890000000  55000000
 9959   1800000000  71000000
 17736  1530000000  45000000
 9235   1750000000  70000000
 1078   1820000000  59000000
 5104   1510000000  38000000
 9625   1610000000  75000000
 15012  1230000000  72000000
 2516   1320000000  56000000
 17685  1970000000  43000000
 654    1310000000  42000000
 ...           ...       ...
 14553  1600000000  71000000
 11638  1970000000  78000000
 11566  1620000000  58000000
 11473  1400000000  70000000
 3398   1770000000  68000000
 13367  1640000000  45000000
 14396  1960000000  43000000
 16673  1350000000  49000000
 991    1870000000  57000000
 9470   1940000000  78000000
 8576   1430000000  69000000
 18972  1340000000  36000000
 15341  1300000000  50000000
 14745  1560000000  68000000
 3401   1520000000  54000000
 911    1670000000  39000000
 1907   1470000000  75000000
 5603   1560000000  70000000
 3963   1440000000  49000000
 7563   1430000000  58000000
 14563  1650000000  39000000
 12271  1820000000  49000000
 14340  1380000000  77000000
 7375   2000000000  71000000
 12411  1650000000  58000000
 6500   1470000000  52000000
 19857  1670000000  60000000
 14528  1870000000  75000000
 899    1800000000  45000000
 12706  1230000000  54000000

 [14000 rows x 2 columns],           deposit     stock
 11705  1630000000  46000000
 5449   1860000000  72000000
 6225   1710000000  75000000
 19870  1250000000  65000000
 15293  1650000000  38000000
 11459  1660000000  46000000
 11098  1510000000  74000000
 18162  1240000000  67000000
 1663   1430000000  39000000
 18390  1560000000  42000000
 6861   1280000000  38000000
 11965  1860000000  71000000
 2375   1530000000  36000000
 3114   1320000000  78000000
 15440  1660000000  36000000
 9457   1280000000  48000000
 10537  1820000000  69000000
 4848   1630000000  38000000
 16832  1980000000  42000000
 11172  1760000000  71000000
 16807  1290000000  56000000
 10338  1360000000  72000000
 264    1240000000  66000000
 11567  1890000000  59000000
 19401  1390000000  47000000
 7224   1670000000  77000000
 14376  1850000000  43000000
 15651  1310000000  39000000
 15837  1510000000  70000000
 19641  1600000000  48000000
 ...           ...       ...
 7301   1890000000  74000000
 8116   1500000000  43000000
 18398  1680000000  42000000
 18064  1860000000  73000000
 16023  1280000000  46000000
 11712  1660000000  38000000
 6984   1620000000  57000000
 6661   1230000000  73000000
 16411  1390000000  67000000
 1800   1840000000  77000000
 12031  1630000000  53000000
 17653  1420000000  38000000
 15306  1970000000  79000000
 17619  1900000000  36000000
 14048  1490000000  66000000
 19007  1300000000  65000000
 15809  1970000000  44000000
 9816   1410000000  67000000
 933    1360000000  37000000
 2766   1960000000  38000000
 8361   1790000000  49000000
 12282  1400000000  51000000
 11178  1550000000  58000000
 12593  1770000000  39000000
 4534   1650000000  45000000
 48     1790000000  41000000
 2610   1260000000  70000000
 17994  1500000000  76000000
 2944   1870000000  67000000
 19335  1990000000  78000000

 [6000 rows x 2 columns]]